### ISSUE TITLE
Request: some kind of <noscript> fallback support for text parts

### ISSUE THREAD

**Issue by JobLeonard** [idyll-lang/idyll#116]
Hey! I wish I discovered this before writing out all the logic [the flame maps demo page](http://linnarssonlab.org/flamemaps/) in React. It would have simplified my life a lot... 

Anyway, I noticed that if you turn JS off on any of the demos, the entire webpage remains blank. That's because of React, I suppose. I had the same thing, and I fixed it by [manually duplicating all the text parts of my website inside the `<noscript>` tag](https://github.com/linnarsson-lab/flamemaps/blob/master/public/index.html) of the index page. Since it's text only, and not that big of a webpage, it doesn't add much overhead.

I know the whole point of Idyll is to make an interactive website, but some form of graceful degradation would be nice I think.

**Comment by mathisonian** [comment]
Thanks @JobLeonard! 

Most of the demos were posted before we added the [server side rendering](https://idyll-lang.github.io/examples/server-side-rendering/). This is enabled by default in new projects, so readers without JavaScript will still get a reasonable experience

**Comment by JobLeonard** [comment]
Ah nice! Would it take a lot of effort to update the existing examples to show off this new functionality?
