### ISSUE TITLE
Passing boolean values to components

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll#12]
`[Loader src:"true" /]` and `[Loader src:1 /]` both work, but `[Loader src:true /]` fails with a message like `Error parsing input at line 14, column 72`. Is there a way to pass boolean props to component that I'm perhaps missing?

**Comment by rreusser** [comment]
Disregard. Looks like backticks e.g. ``verbose: `true` `` will do it.

**Comment by mathisonian** [comment]
@rreusser I've got an issue for this and a couple other things on the compiler repo https://github.com/idyll-lang/idyll-compiler/issues/2. There's an undergraduate student who is going to start working on some of these soon and help clean up the rough edges with the compiler

**Comment by mathisonian** [comment]
fixed in #9
