### ISSUE TITLE
Monorepo cleanup 

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#122]
I suppose we should close out the other repos and make sure that their issues are moved over to this one. We can just tag them with the component that they belong to.

**Comment by bclinkinbeard** [comment]
:+1:

**Comment by mathisonian** [comment]
Okay - all the issues have been migrated over and tagged according to their source repository.

I believe we can now delete the follow repos (unless there is a reason to keep them for posterity?)

- https://github.com/idyll-lang/idyll-component
- https://github.com/idyll-lang/idyll-interactive-document
- https://github.com/idyll-lang/idyll-default-components
- https://github.com/idyll-lang/idyll-compiler
- https://github.com/idyll-lang/idyll-mono

In doing this I realized that in order to keep the URL https://idyll-lang.github.io/editor/ (which I think we should) we'll have to maintain the `editor` outside of the monorepo. I think this is fine since it isn't really a component anyways.

**Comment by bclinkinbeard** [comment]
Pretty sure we can delete them. But maybe we should both clone them and store them first, just in case. :)

Agreed re: the link, but I wonder if there's a way to keep it in the monorepo. It's been really handy for dev.

**Comment by mathisonian** [comment]
I've deleted `idyll-mono` and added deprecation warnings to the others. There may be some links to them floating around, so its probably better to not break those and just keep the repos with warnings for now
