### ISSUE TITLE
Equation parsing problem

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#135]
<a href="https://github.com/rreusser"><img src="https://avatars0.githubusercontent.com/u/572717?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rreusser](https://github.com/rreusser)**
_Tuesday Jun 13, 2017 at 14:33 GMT_
_Originally opened as https://github.com/idyll-lang/idyll-compiler/issues/30_

----

This equation succeeds:

```
[Equation display:`true`]
\sum_{j=0}^n x^{j} + \sum x^{k}
[/Equation]
```
and renders like this:

<img width="182" alt="screen shot 2017-06-13 at 10 32 33" src="https://user-images.githubusercontent.com/572717/27087690-b19e3992-5023-11e7-8e1a-6df0a6b4bdfc.png">

While this equation fails:
```
[Equation display:`true`]
\sum_{j=0}^n x^{j} + \sum_{k=0}^n x^{k}
[/Equation]

and renders like this:

```
<img width="194" alt="screen shot 2017-06-13 at 10 32 04" src="https://user-images.githubusercontent.com/572717/27087652-923307cc-5023-11e7-9493-3cff3a9ade0e.png">

It seems like maybe the `_` is interfering with markdown parsing, but I'm not 100% sure yet.

As usual, work around is `[Equation latex:"..."/]`

**Comment by joshuahhh** [comment]
I've run into this problem as well. As a simple example,

```Compare [Equation]x_0[/Equation] to [Equation]y_0[/Equation] and you will discover...```

renders as

<img width="495" alt="screen shot 2017-12-14 at 12 33 07 am" src="https://user-images.githubusercontent.com/643799/33982722-62ff9802-e066-11e7-86e1-c77d33b8d7a1.png">

My guess is that the `_`s are being treated with a higher precedence than `[Equation]`, which is surprising to me.

(But that work-around works. Thanks!)
