### ISSUE TITLE
Components that modify their children don't work

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#142]
<a href="https://github.com/bclinkinbeard"><img src="https://avatars2.githubusercontent.com/u/140343?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bclinkinbeard](https://github.com/bclinkinbeard)**
_Thursday Jul 20, 2017 at 16:48 GMT_
_Originally opened as https://github.com/idyll-lang/idyll-interactive-document/issues/2_

----

```javascript
class Maximized extends Component {
  render() {
    const maxKids = React.Children.map(this.props.children, c => {
      return React.cloneElement(c, {
        className: 'maximized'
      })
    })

    return (
      <div>
        {maxKids}
      </div>
    )
  }
}
```

does not produce children with the `maximize` class applied as expected.

**Comment by bclinkinbeard** [comment]
Fixed by `idyll-document` refactor
