### ISSUE TITLE
Performance concerns in scroll monitoring

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#157]
[These `getBoundingClientRect()` calls](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L39-L41) will cause reflows which may lead to some jank on scrolls. While we're making changes to the refs and scroll logic, it'd probably be worthwhile to see what can be done to avoid these calls. As I see it there are two options:

1) cache their values and update them on relevent events
2) lean more heavily on `scrollmonitor` and just use the values that it already calculates more directly

I think I'd be okay with (2), the only obvious downside being that it only handles vertical and not horizontal scrolling.

**Comment by bclinkinbeard** [comment]
Dang, I didn't realize that caused a reflow. Lines 40 and 41 should happen at the top of `getRefs()` but I'm not sure how to get around the one on line 39. There is no event for a node having changed size, is there?
