### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#188]
I think the recent compiler changes introduced a bug. Getting `RangeError: Invalid array length` from `parser.js` when running the editor.

**Comment by mathisonian** [comment]
Can you confirm that the compiler grammar rebuilt? (either thru the top level postinstall hook or `npm run build` in the compiler)

**Comment by mathisonian** [comment]
I'm guessing you were hitting an error on this line https://github.com/idyll-lang/idyll/blob/master/packages/idyll-compiler/src/parser.js#L58

There is a potential out-of-bounds issue to hit which might have been triggered by the grammer and lexer being out of sync. pushed a check for that in https://github.com/idyll-lang/idyll/commit/17f26e4afa8696bfd6689992bbc1290047487d41
