### ISSUE TITLE
remove src prop from idyll document?

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#194]
On second thought I'm not sure how much sense it makes to include the compiler as a dependency in `idyll-doc`: there are a fair number of libraries that that depends on that would bloat the default bundle size quite a bit in the case that people are using the command line tool - not sure its worth it to avoid needing to write `<IdyllDoc ast={compile(src)} />` in some use cases

**Comment by bclinkinbeard** [comment]
Can we measure the bundles? I don't understand the comment about the CLI though. And when would you have access to the AST without also having to have the compiler?

**Comment by mathisonian** [comment]
Yeah, I can measure and post the bundle sizes.

For the CLI the bundle that is sent to the browser has the AST precompiled https://github.com/idyll-lang/idyll/blob/master/packages/idyll-cli/src/client/build.js#L7

**Comment by bclinkinbeard** [comment]
Ah, true. Do we care about bundle size in that scenario though? I guess I'm not quite sure what the use cases are for the CLI now that everything can happen in the browser.

**Comment by mathisonian** [comment]
I think we do. For folks who want to publish something with Idyll (bloggers, journalists, etc) and have full control to customize, the CLI (or `idyll` package directly) is still the easiest way to go. 

The more that we can do to make the output that `idyll` generates "production-ready" the better imo.

**Comment by bclinkinbeard** [comment]
Tree shaking ftw? 😂

I actually don't have a problem with yanking it if you want. If we want to revisit it later we can.

________________________________
