### ISSUE TITLE
Support frontmatter

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#200]
Compiler doesn't seem to like it. Can it just ignore it? Would be useful for/from other tools...

**Comment by mathisonian** [comment]
Are you imagining jekyll style front-matter?

```
---
option: value
otherThing: my-post-slug
---
```

**Comment by bclinkinbeard** [comment]
I think the extent to which I thought about this was just enabling files that are part of an existing project (like a file based blog or CMS) to be fed into the compiler.

________________________________

**Comment by mathisonian** [comment]
Okay - can you give examples of what that would look like? We'll need some way for the compiler to figure out where the Idyll markup starts.

BTW - i'm very open to adding structured front matter - multiple people have asked for this

**Comment by bclinkinbeard** [comment]
Sure, looks like the files I tried use the same delimiters as what you posted. I don't think I knew there were different kinds of front matter. 😬 

```
---
	title: Up and running with ES6 and React in under 5 minutes
	date: 2015-3-9
	dateLabel: September 2015
	description: Really cool stuff
	collection: posts
---
```

I hadn't really thought about structured front matter. What's the tl;dr?

**Comment by mathisonian** [comment]
Okay - by structured front-matter I just mean the format we've shown above where Idyll actually parses the data, e.g. to fill in header, meta-data, etc.

Having the compiler just ignore it will be a quick first step and we can discuss how it makes sense to parse it.

**Comment by mathisonian** [comment]
Closed in https://github.com/idyll-lang/idyll/pull/244
