### ISSUE TITLE
Post v2 Wish List

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#202]
- better theme and layout support (via CSS builds?)
- basic analytics on site/editor

## Not So Much Wishes
- I keep coming back to the idea of a "standard" format for serializing React UIs. Right now we have the AST the compiler creates and the JSON we convert it to for automating `createElement`. I think it could make sense to pick a format and ensure all tools write it and/or read it. Seems as if it could encourage others tools to support the format.
- Similar question, should we spec-ify the input syntax? Explicitly defined superset of Markdown?
- Contact the https://github.com/Thinkmill/react-markings folks?

**Comment by mathisonian** [comment]
- https://github.com/idyll-lang/idyll/issues/70
- https://github.com/idyll-lang/idyll/issues/200
- blog engine

**Comment by mathisonian** [comment]
A method for editing component code in the browser and have it update

**Comment by mathisonian** [comment]
Redesign `idyll-lang.org` with a landing page and links to examples, editor, docs, etc

**Comment by mathisonian** [comment]
User defined functions in expression, so i could do, e.g. 

```
[Button onClick:`myCustomFunction(x)` /]
```
