### ISSUE TITLE
How to deal with wrapped components when manipulating children

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#205]
An unfortunate side effect of injecting wrapper components is that it breaks logic for components that manipulate their children. For example, the `Feature` component needs to look for a `Feature.Content` child component; another component may want to add a "selected" class to one of its children based on a provided prop. 

This behavior becomes harder to implement in components because they can't just check the child component type (which might be `Wrap`) or child component props, and instead they need to check either the child component *or* the child's child component. 

I'm not sure if there's any easy way around this -- one possibility is giving the wrapper a custom name based on its child, and making sure that the wrapper accepts the same props as its child? Another possibility is providing some sort of utility function to make this easier for component authors.

**Comment by bclinkinbeard** [comment]
Ah, good catch. I wonder if we should not wrap components that are already under a wrapper. Or give components like Feature a way to signal their children shouldn't be wrapped?

________________________________

**Comment by mathisonian** [comment]
I think we still want them wrapped because its totally valid for children to call `updateProps`, etc

**Comment by mathisonian** [comment]
I've created a small helper module to take the tedium out of this: https://github.com/idyll-lang/idyll-component-children.

This should be added to the custom component docs.
