### ISSUE TITLE
( immediately following a code tag

### ISSUE THREAD

**Issue by k24dizzle** [idyll-lang/idyll#234]
`[code](n - 1)!/2 possible paths[/code]`

 `(` immediately following a code tag throws an error?

**Comment by mathisonian** [comment]
I think its reading this as a link (related to https://github.com/idyll-lang/idyll/issues/129). Workaround is to put it in backticks instead of a codeblock, e.g. ``` `(n - 1)!/2 possible paths` ``` or similarly use an equation tag `[equation latex:"(n - 1)!/2" /]`

**Comment by mathisonian** [comment]
Or just add a space before the paren
