### ISSUE TITLE
support local themes

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#24]
A good suggestion from @ejb

If someone wants to use a custom theme, it would be very useful to be able to specify a local CSS file, e.g.

```
idyll index.idl --theme ../my-custom-theme.css
```

The same logic could be applied to `layout`.

**Comment by bclinkinbeard** [comment]
I was wondering about this as I reviewed the code. Could likely be done transparently by checking for a slash in the input. If a slash exists treat it as a file path, otherwise assume it's a name to be pulled from default location.

I can probably create a PR for this if that sounds good.

**Comment by mathisonian** [comment]
That makes sense to me, I don't think it needs to be more complicated than checking a a path exists.
