### ISSUE TITLE
Better support for full-width components

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#245]
A common scenario in Idyll is that a user wants to embed a component that spans the full width of the page. With the current setup (where everything lives inside of a container with some fixed max width), this is kind of a pain because you have to manually figure out how to add negative margins to make it occupy the full width of the page rather than the full width of the container.

A better solution might be handled at the compiler level, where a user could specify a component as full width (or the component could provide some meta-data to tell the compiler that it should be rendered full width). For example, consider the following markup:

```
Regular text

Regular, non-full width component:
[Range /]

A full width component:
[Slideshow fullWidth:true /]

More regular text.
```

The compiler could turn this into something like:

```
<div>
    <div className="text-container">
       <p>
          Regular text
       </p>
       <p>
       Regular, non-full width component:
       <Range />
       </p>
       <p>
       A full width component:
       </p>
     </div>
     <div className="full-width">
       <Slideshow />
     </div>
    <div className="text-container">
       <p>
          More regular text.
       </p>
    </div>
</div>
```

**Comment by rreusser** [comment]
Is this complete? I've been using this feature and it seems to work great!

**Comment by mathisonian** [comment]
Yeah! I'm still working on adding it to the docs site, but it is in the latest verison.  In addition to `fullWidth:true`  you can also do:

```
[FullWidth]
   [TextContainer]
      This text is in the normal column
   [/TextContainer

   [div]This is unconstrained[/div]
[/FullWidth]
```
