### ISSUE TITLE
React Warnings for camelcased props

### ISSUE THREAD

**Issue by evanfrawley** [idyll-lang/idyll#261]
When running locally, I'm getting 3 errors (though there may be more that are lurking in the codebase) for camel cased props. 

Here's the following warning in the terminal output:

```
Warning: React does not recognize the `hasHook` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hashook` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

This is also the case for:
- refName
- updateProps

**Comment by mathisonian** [comment]
Thanks @evanfrawley, these warnings are annoying but shouldn't affect the functionality of your application at all. They'll be gone once #252 gets merged in.
