### ISSUE TITLE
`.idl` file extension could be confused with WebIDL's `.webidl`

### ISSUE THREAD

**Issue by cvan** [idyll-lang/idyll#263]
Web-browser standards use [WebIDL](https://heycam.github.io/webidl/), which often has files ending with `.webidl` (example in [Firefox](https://dxr.mozilla.org/mozilla-central/source/dom/webidl)).

**Comment by mathisonian** [comment]
Thanks @cvan I didn't know about WebIDL. It might be judicious for us to switch to `.idyll` at some point to avoid any confusion (and none of the infrastructure here really depends on that file extension).

**Comment by mathisonian** [comment]
Fixed in https://github.com/idyll-lang/generator-idyll/commit/8268519692eea667b3bc99d01794bf9faa1f6841 by renaming `index.idl` to `index.idyll` in the project generator. The syntax highlighters already match on `.idyll`, so no need to update those.
