### ISSUE TITLE
Reloading page breaks onEnterViewFully if not at top of page

### ISSUE THREAD

**Issue by leemeli** [idyll-lang/idyll#265]
onEnterViewFully stops working if you are in the middle of the page (/anywhere but the very top) and reload the page. Here's an example:

http://students.washington.edu/leemeli/build/

**Comment by mathisonian** [comment]
Thanks for pointing this out @leemeli - I'm able to reproduce it as well. It seems clear that the initial scroll offset isn't being factored in properly, but I'm trying to figure out whether that is an issue with our code or https://github.com/stutrek/scrollMonitor/ which we use under the hood.

**Comment by mathisonian** [comment]
This is fixed by https://github.com/idyll-lang/idyll/pull/277 and the update is available on npm in version `2.5.2`
