### ISSUE TITLE
Interesting behavior: Headings rendered as custom React components?

### ISSUE THREAD

**Issue by iocat** [idyll-lang/idyll#300]
Hi! So great project so far. I am integrating IdyllDocument component into my blog. 
I found an interesting strange behavior, but I'm happy to use in my project. 

## Expected Behavior
As part of the language syntax, a heading in Idyll
```
    ## This is a heading.
```
becomes
```
<h2> This is a heading. </h2>
```
in HTML

## What I did
In my project, I wanted to have custom styling for headings (all my headings are actually `<div></div>` HTML elements), so I created H1->H6 React components. So in the idyll document, I would have 
```
[H2] This is a heading [/H2]
```

## Actual behavior ( here is the interesting part )
While importing the custom headings H1->H6, I wrote the Idyll document as
```
     ## This is a heading.
```
**The React Component H2 is used instead of the `<h2></h2>` tags.** And my component is rendered as expected: 
```
<div class="custom-styling-for-h2"> This is a heading </div>
``` 
in HTML

This is GREAT though because writing `[H$] [/H$]` all the time is quite tedious, and `#` makes Idyll cleaner and is backward compatible to the Idyll specs!

I hope this behavior won't be changed in the future. Is there an explanation to this?

**Comment by mathisonian** [comment]
This is an effect of how we do component resolution - 

First, we convert markup styles to idyll component tags, e.g. `*italic*, **bold**`, becomes `[i]italic[/i], [b]bold[/b]`and then these tags go through the component lookup algorithm the same as the ones that you wrote by hand. 

The effect that you're seeing isn't explicitly documented, but I think its a reasonable behavior and goes along with the general principle that when you provide custom components they override the standard idyll components or html tags. @andrewosh you have any other thoughts on this?

**Comment by andrewosh** [comment]
Nope no major additional thoughts, though it's possible that this could be undesirable in other situations (at least when it's done implicitly -- can be confusing). It does seem to make sense for this to be the default behavior, but we should probably :
1. Add a bit more documentation describing the component resolution order (first custom components, then defaults, then HTML tag). I can see why it's unclear at first if this is a feature or a bug :)
2. (perhaps in a need-driven way) Add ways of overriding this default behavior. Perhaps you only want to use the `H2` tag when it's explicitly created as a component, for example.

**Comment by mathisonian** [comment]
To be more explicit @iocat: I don't consider this a bug and it won't change anytime soon. We'll update the docs to mention it.
