### ISSUE TITLE
[idyll-ast] Should setProperty(), setProperties() and removeProperty() check for a string node?

### ISSUE THREAD

**Issue by iocat** [idyll-lang/idyll#301]
Consistently, most of the functions in the idyll-ast module has a check if a node is a string, and maybe ignore it (if suitable). But these three functions
```js

const setProperty = function(node, key, value) {
 let hasSet = false;
  const isArr = Array.isArray(value);
  node[1] = node[1].map((element) => {
      if (element[0] === key) {
        hasSet = true;
        return [element[0], isArr ? value : ['value', value]];
      }
      return element;
  });
  if (!hasSet) {
    node[1] = node[1].concat([[key, isArr ? value : ['value', value]]]);
  }

 return node;
};

const setProperties = function(node, properties) {
  Object.keys(properties).forEach((key) => {
    node = setProperty(node, key, properties[key]);
  })
  return node;
};

const removeProperty = function(node, key) {
  node[1] = node[1].filter(([propName, propVal]) => {
    if (propName === key) {
      return false;
    }
    return true;
  })
  return node;
};

```
 didn't have a type-guard against string node, so accessing `node[1]` can return a character. 

These functions are exported, so they might introduce bugs if they are used by third party module? 

setPropert[y|ies]'s counterparts (getPropert[y|ies]) have checks for string node, however.

**Comment by mathisonian** [comment]
Thanks for pointing this out @iocat - I've submitted a PR to add these checks. @pavankUW is working on adding some additional tests to the `idyll-ast` module as well.
