### ISSUE TITLE
Typescript Types for idyll, idyll-ast, idyll-document, and idyll-compiler

### ISSUE THREAD

**Issue by iocat** [idyll-lang/idyll#303]
Hi, 

This is not an issue. 

I just wanna let everyone know that I've been working on some DefinitelyTyped packages for idyll. 

**idyll-ast**: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/idyll-ast
**idyll**(idyll-cli): https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/idyll
**idyll-compiler**: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/idyll-compiler
**idyll-document**: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/idyll-document

It also added some docs by what I understand from the code, but it might not correspond to runtime behavior. So would it be ok if someone who understands the code/the architecture better double check?

Please feel free to close this issue :)

**Comment by mathisonian** [comment]
Thanks @iocat, this is great!

I'll spend some time looking through the comments and let you know if I have any suggestions / changes
