### ISSUE TITLE
Browsersync should not watch INPUT_DIR

### ISSUE THREAD

**Issue by andrewosh** [idyll-lang/idyll#311]
If all static assets are contained in a static assets directory (as per #308), then Browsersync should not have to watch the input directory for file changes (i.e. in included images). 

This will resolve any ambiguity in asset loading that could arise from mismatches between static assets copied into the build directory (all files in `static/`), and those in the top-level input dir during `watch` mode.

Since this is a breaking change (static assets in existing projects that aren't stored in the static asset dir will no longer be watched), this fix should wait for the next major version bump.

**Comment by mathisonian** [comment]
Fixed by #335
