### ISSUE TITLE
Asynchronous data loading API

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#317]
Syntax like

```
[data name:"..." source:"..." async:true /]
```

would be killer.

**Comment by manjhawar96** [comment]
Questions: 
1. How do components know that this is a data from another source, rather than just treat it like a variable? 
2. What should be the initial data?

**Comment by rollaball** [comment]
So will this data be loaded during component mount or in the build phase?

**Comment by mathisonian** [comment]
The idea is that data would be loaded during the mount. The `[data /]` tag as it is currently implemented brings data in during the build phase, but in certain cases (e.g. with some larger data sets) this becomes a performance issue. So to implement this we'd need to add functionality to the `idyll-runtime` to check for any async requests that need to be made and carry those out. 

We would also need to update the AST schema so that `data` tags with an async prop will validate.

**Comment by mathisonian** [comment]
As @manjhawar96 pointed out - there is the issue of initial data -- I think this should be user specifiable but we should think through what a reasonable default would be (`undefined`? `null`? `[]`?).

**Comment by rollaball** [comment]
If we do pick undefined or null, the components might need to be updated to handle this.
I think user specified or empty array/object might be a good choice.

**Comment by mathisonian** [comment]
That's a good point @rollaball - I think empty array as the default with an optional `initalValue` param would work well

**Comment by rollaball** [comment]
I get the following error in idyll-cli tests when I try to import `csv-parse` in the idyll-document.
 ```
 FAIL  test/minified-project/test.js (31.736s)
  ● Console

    console.error src/index.js:186
      JS_Parse_Error {
        message: 'Unexpected character \'`\'',
        filename: 0,
        line: 8335,
        col: 18,
        pos: 277454 }
```
Any idea why this might be happening?
