### ISSUE TITLE
Issues building basic projects

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#322]
It seems some recent updates are causing issues with Idyll builds. In particular, the builds run as expected, but the process never exits:

How to reproduce:
```
$ yo idyll
$ cd new-idyll-project
$ npm run build # hangs forever
```

@andrewosh I'm not sure if this has to do with the updates you made to get the tests to run properly

**Comment by andrewosh** [comment]
Hmm I'll check to see if this is caused by any recent changes -- the only change that seems like it could affect process termination happens during testing watch mode, but that hasn't been an issue. Checking now

**Comment by andrewosh** [comment]
So apparently the `--no-minify` option isn't working correctly, but manually commenting out the minification step both fixed the above error, and the build process exited.

**Comment by mathisonian** [comment]
[This issue](https://github.com/idyll-lang/idyll/issues/125) with the option, I'm guessing? I'll try to recreate what you're seeing -- the hanging behavior I had was coming from the build for https://mathisonian.github.io/idyll-comic/, i guess there might be some difference from the starter template, although I'm not sure what that is.

**Comment by mathisonian** [comment]
I've pushed a hotfix for this that solves the problem for freshly started projects. Still not sure what's up with https://mathisonian.github.io/idyll-comic/ specifically but will investigate further. It may be specific to some component in that project.
