### ISSUE TITLE
undo/redo/bookmarked state support

### ISSUE THREAD

**Issue by mhalle** [idyll-lang/idyll#325]
The Idyll runtime does a nice job of packaging up a page's state. That opens up the possibility of providing undo/redo support. 

The simplest option would be to maintain a state stack. A more elaborate option (which could open up the possibility of saving and merging state, would be to use something like [automerge](https://github.com/automerge/automerge) for state management.

New "Undo" and "Redo" directives that could be tied to buttons.  

The same state could be serialized as query parameters in a URL, forming bookmark-able state.

**Comment by mathisonian** [comment]
Automerge looks really cool, although we don't support collaborative use at this time, so it might make sense to start with the simpler approach of maintaining our own state stack

**Comment by mathisonian** [comment]
Here's a (very) basic version of bookmarked state using the context API:

```js
const queryString = require('query-string');

const updateURL = (qs) => {
  var newUrl = window.location.protocol + "//" + window.location.host + window.location.pathname + '?' + qs;
  window.history.pushState({ path: newUrl }, '', newUrl);
}

module.exports = (ctx) => {

  if (location.search) {
    // Merge initial state with the state from URL if it exists:
    const parsed = queryString.parse(location.search);
    ctx.update(parsed)
  } else {
    // Otherwise serialize the initial state to the URL
    const data = ctx.data();
    const stringified = queryString.stringify(data);
    updateURL(stringified);
  }

  // Update the url when data changes
  ctx.onUpdate((newData) => {
    const stringified = queryString.stringify(
        Object.assign({}, queryString.parse(location.search), newData));

    updateURL(stringified);
  })
}
```

it doesn't support forward/rewind yet, but still pretty cool!

![idyll-state-url](https://user-images.githubusercontent.com/1074773/43984239-2d443da2-9cb4-11e8-9a4e-6193e35cea16.gif)

for more info on the context API see https://idyll-lang.org/docs/advanced-configuration

**Comment by mathisonian** [comment]
Closing this in favor of https://github.com/idyll-lang/idyll-plugin-url-state. This plugin encapsulates the majority of this functionality and we can continue to make specific improvements and work through issues there.
