### ISSUE TITLE
Links to GitHub source in gallery examples blocked by "Content Security Policy"

### ISSUE THREAD

**Issue by bryangingechen** [idyll-lang/idyll#331]
I'm not sure if this is the right place to post this, but when I open https://idyll-lang.org/gallery/take-a-walk-on-the-idyll-side in Firefox 60.0.2 and left-click on the "View Source" link at the very bottom, I get an error page in Firefox stating "Blocked by Content Security Policy

This page has a content security policy that prevents it from being loaded in this way.

Firefox prevented this page from loading in this way because the page has a content security policy that disallows it."

In Chrome 67.0.3396.87, I just get a blank page.

With either browser, if I open the link in a new window or tab it works as expected. It also works fine if I visit the page from https://mathisonian.github.io/idyll/a-walk-on-the-idyll-side/ .

It seems that this affects other pages in the gallery as well, e.g. https://idyll-lang.org/gallery/the-barnes-hut-approximation .

**Comment by mathisonian** [comment]
Actually I take that back - I'm seeing issues on the page https://idyll-lang.org/gallery/the-math-of-card-shuffling due to it being HTTP instead of HTTPS, but am not able to reproduce the exact errors that you are seeing in Firefox 61 or Chrome 67

**Comment by bryangingechen** [comment]
OK, let me try to clarify. If I open https://idyll-lang.org/gallery/take-a-walk-on-the-idyll-side this link and click on the "View Source Code" link in the banner at the top then it indeed directs me to github perfectly fine.  On the other hand, if I scroll all the way down on the page in the inner frame and click the link in the sentence "View the full source for this article on GitHub." then I still seem to get the error I described.

**Comment by mathisonian** [comment]
Ahh okay - thanks for the clarification. I am seeing the same thing.

**Comment by mathisonian** [comment]
Fixed in #475
