### ISSUE TITLE
newest V3 `idyll` and `idyll publish` doesn't seem to work with pre-V3 projects

### ISSUE THREAD

**Issue by tanalan** [idyll-lang/idyll#345]
I updated to the latest idyll via `npm i -g idyll@latest`, and `idyll` starts the dev server fine in projects newly created with `idyll create`.
However, in projects I created before updating to V3, running `idyll` and `idyll publish` don't seem to produce any behavior in my terminal (even after restarting terminal).
<img width="1132" alt="screen shot 2018-06-26 at 10 13 39 am" src="https://user-images.githubusercontent.com/12927245/41928315-aa11ce3e-7929-11e8-9fa3-cb1ed6214b31.png">

**Comment by mathisonian** [comment]
What version of node are you using?

**Comment by mathisonian** [comment]
This might be some issue with node `v10`, which I noticed swallows error output in some cases.

**Comment by tanalan** [comment]
I have v8.11.3
