### ISSUE TITLE
setting range for a chart

### ISSUE THREAD

**Issue by batson** [idyll-lang/idyll#348]
The domain prop for `Chart` works as expected. Is there supposed to be an ability to set the range?

An example where I would like to have the range of the chart be higher than the max value is below. I took the syntax from a [default](https://github.com/idyll-lang/idyll/blob/d5254b7f3f9a9fb6016f8c6edf6bdb0dce7987de/packages/idyll-components/src/chart.js#L77) in chart.js. Is there an easy way to express this? 

Thanks for the beautiful tool, and I appreciate the guidance!

```javascript
[Chart
 equation:`(t) => 1 - t**2`
 domain:`[-2, 2]`
 range:`[-1,2]`
 samplePoints:1000 
/]
```

**Comment by mathisonian** [comment]
Thanks @batson - I would expect the code that you have to work, however it looks like the range prop isn't being passed through to the chart output as expected. I've submitted a PR to fix this: https://github.com/idyll-lang/idyll/pull/349

The chart component needs a little bit of love still. If you can't get it to do what you want the https://github.com/idyll-lang/idyll-vega-lite or https://github.com/jerairrest/react-chartjs-2 components are also good options.

**Comment by mathisonian** [comment]
This has been released to npm. The updated component should be installed automatically in future posts that are made with `idyll create`. To upgrade an existing post, run `npm i --save idyll-components@latest`
