### ISSUE TITLE
Adopt Prettier

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#359]
People seem to like [prettier](https://github.com/prettier/prettier). 

Should we use it?

**Comment by BTBTravis** [comment]
Seems like a good fit for the project. Looking over the basic install options (Editor plugins, CLI, Pre-commit hooks) I think installing as a dev dependancy and using a pre-commit hook seems the best choice for this project?

I've been wanting to explore prettier and implementing this would be a good opportunity. There is really not to many config options. Here are the defaults with values I think we should override for idyll, only one I'm in sure about. Do you want the `Pragma` as in:
```javascript
/**
 * @prettier
 */
```
at the top of files?

------


<table >
<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Option</th>
<th scope="col" class="org-left">Default</th>
<th scope="col" class="org-left">idyll</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">printWidth</td>
<td class="org-left">80</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">tabWidth</td>
<td class="org-left">false</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">useTabs</td>
<td class="org-left">false</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">semi</td>
<td class="org-left">true</td>
<td class="org-left">false</td>
</tr>


<tr>
<td class="org-left">singleQuote</td>
<td class="org-left">false</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">trailingComma</td>
<td class="org-left">none</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">bracketSpacing</td>
<td class="org-left">true</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">jsxBracketSameLine</td>
<td class="org-left">false</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">arrowParens</td>
<td class="org-left">avoid</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">requirePragma</td>
<td class="org-left">false</td>
<td class="org-left">?</td>
</tr>


<tr>
<td class="org-left">insertPragma</td>
<td class="org-left">false</td>
<td class="org-left">?</td>
</tr>


<tr>
<td class="org-left">proseWrap</td>
<td class="org-left">preserve</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by mathisonian** [comment]
> installing as a dev dependancy and using a pre-commit hook seems the best choice for this project 

That sounds reasonable to me.

We've been unfortunately inconsistent with semicolons, though the majority of the codebase does use them, so I think it'd be fine to keep the default there.

> Do you want the Pragma?

It seems like this is useful when we want to opt-in to prettier on specific files. While there might be less churn up-front with this option, I think I'd prefer to just go all-in on prettier formatting and skip that... unless there are any known bugs or issues that would prevent us from using it on certain files. 

The only place I'm really concerned about what prettier will do is in the runtime where we are generating code to be eval'd (e.g. here https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/utils/index.js#L6-L31)

**Comment by mathisonian** [comment]
Closed by #436
