### ISSUE TITLE
Use Jest for testing?

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#36]
I've determined that `expect.js` is the reason the tests hang when trying to compare the JS bundles. Node's native `assert` does the same comparison with no delay whatsoever, as does Jest. Since Idyll is creating React projects it seems like Jest would be the best choice for a testing library as it may enable more elaborate testing in the future.

If you're amenable to this change I can have a PR ready in the next couple of days.

**Comment by mathisonian** [comment]
I'd be happy to use Jest. We use it to test the [default components](https://github.com/idyll-lang/idyll-default-components/blob/master/test/components.js) (although at this point its really just making sure that they render without error). A PR would be welcome!

**Comment by bclinkinbeard** [comment]
Implemened in #37
