### ISSUE TITLE
Idyll - V3.0.18  installation fails in Windows 10 platform

### ISSUE THREAD

**Issue by Abhilash-Chandran** [idyll-lang/idyll#364]
**Idyll - V3.0.18  installation fails in Windows 10 platform**
Idyll installation fails in windows 10 platform with dependency warnings pointing to nomnom package and fsevents.

**To Reproduce**
1. Use a windows 10 system.
2. Install **node.js 64-bit** latest version https://nodejs.org/en/download/
3. Update **npm** with the command  `npm install npm@latest -g`
4. Check node and npm versions
`node -v`
v8.11.3
`npm -v`
6.1.0
4. Install Idyll using `npm install -g idyll`

**Expected behavior**
A complete installation of Idyll. At the least following commands should work
`idyll -help`
`idyll create`
`idyll`
`idyll publish`

**Actual behavior as Screenshot**

- Installation ends abrubtly

![image](https://user-images.githubusercontent.com/4489849/42115129-06125288-7bf2-11e8-9c26-a6e6c766ac42.png)

- Idyll commands with no reponse
![image](https://user-images.githubusercontent.com/4489849/42115376-e21c7c68-7bf2-11e8-89bc-d57dd60ae73a.png)

**Desktop**

 - OS: Window 10
 - Browser NA
 - Version 64 bit operating system
 - Node - V8.11.3 - 64 bit - msi
 - npm  - V6.1.0
 - Idyll  - V3.0.18

**Possible alternative**
A possible alternative as suggested by @mathisonian  is to use the Idyll 2.x version which can be installed using the following.
`npm i -g idyll@2`

Verify the installation using  `idyll -help`

and follow the version 2.x documentation - https://v2.idyll-lang.org/docs/getting-started

**Comment by mathisonian** [comment]
Thanks @Abhilash-Chandran. I'm working on a fix for this in https://github.com/idyll-lang/idyll/pull/365 but still need to do some testing to confirm that it solves the issue.

**Comment by mathisonian** [comment]
This was fixed by #365, and the patch is available on npm, `idyll@3.0.19`

**Comment by Abhilash-Chandran** [comment]
I would like to confirm that the following commands worked in windows 10 as expected with the latest `idyll@3.0.19`. 
```
idyll -help
idyll create
idyll
```
Kudos @mathisonian for a quick and clean fix. I will check the publish part once I am ready with a decent write up..
