### ISSUE TITLE
Custom component documentation should be improved

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#371]
Writing custom components is a core part of the idyll authoring experience. The docs should be improved so that it is more easily understood how to create components using the various libraries that idyll integrates with. 

At a minimum we should have separate documentation for 

- Creating a custom component using React
- Creating a custom component using D3

**Comment by tanalan** [comment]
I'd love to handle/self-assign this once I'm more experienced with making custom components :]

**Comment by mathisonian** [comment]
Sounds good - thanks @tanalan!

**Comment by tanalan** [comment]
Nearly a year later, I do feel much more comfortable with React!

Is it fine to separate this issue into two issues -- in particular, one issue for creating a custom component using React, and then one for D3?

One motivation for me asking if b/c I'd like to start on the documentation for React, and I haven't used d3 before, heh

**Comment by mathisonian** [comment]
Let's keep it as one issue because I think it may be weird to have one without the other. However, I'm happy to handle the D3 part. Much of it can be cribbed from https://idyll-lang.github.io/idyll-d3-component/ anyways, but I think it deserves to be elevated to the main docs.

**Comment by tanalan** [comment]
Made some finalizations to this:
https://github.com/tanalan/idyll-react-components-tutorial
Think it seems good to go for this :O

**Comment by mathisonian** [comment]
Thank you @tanalan!! We're working on some updates to the documentation website and will post a link to this on the next deployment. 

I think this is going to be a huge help for people getting started.
