### ISSUE TITLE
variable declaration shorthand

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#389]
Currently `var`s and `derived`s must be declared one at a time, and each declaration must specify separate `name` and `value` properties. There are also often many `var`s and `derived`s declared near each other at the top of idyll documents. e.g https://github.com/mathisonian/dimensionality-reduction/blob/master/index.idyll#L9-L19.

An alternative would be to allow variables to be defined like:

```
[var 
   varName1:"varValue1" 
   varName2:"varValue2"
  /]
```

we'd have to take care to make sure this is backwards compatible with the existing name/value definitions, but IMO it would make for nice sugar over the current syntax.

**Comment by hmuar** [comment]
I was going to try for the suggested syntax:
```js
[var 
   varName1:"varValue1" 
   varName2:"varValue2"
  /]
```
But I was thinking that if input is this:
```js
[var 
   name:"homer" 
   value:32
  /]
```
It'd be tough to tell whether the user wants a normal [var /] component or if the user is going for the shorthand notation and want to declare two vars called "name" and "value". Unless maybe we make an iffy assumption like:

component definition + properties in single line --> normal [var /]
component definition + properties is multiline --> shorthand notation

What do you think?

**Comment by mathisonian** [comment]
I think you bring up a really good point about the ambiguity here. I'm not sure this change would be worth it given that. I floated the idea of adding some completely different syntax for this a while ago, something like:

```
- var x = 10
```

but it seems like folks weren't too bothered by the existing syntax then to want the change. I'm not sure if opinions have changed since then, but maybe everything is fine as is here?

**Comment by hmuar** [comment]
I think that could be good. To me, var feels like something a bit different than built-in components because the other components feel like they tied to some type of presentation or view, e.g. [button /], [Scroller]. Maybe because I might still be intuitively mapping *idyll component* directly to *presentational React component* in my head.

I think because things like *var* are more data/programming constructs, it could be great to do something like you suggest so it looks different than presentational component syntax.

But my reasoning here might start clashing with your design philosophy. If I had to stay consistent with what I'm saying, i'd have to think that the *[Conditional] if component* should be changed in a similar way since it acts like a programming construct too.

**Comment by mathisonian** [comment]
You are right that they are conceptually different. The reasoning behind that was to limit the amount of additional syntax that users need to learn, which I think has some benefits. 

One of the goals was to avoid making Idyll a _templating language_, so we didn't include things like control flow, loops, etc. that are more programming constructs. However these features have been worming their way in a little bit through components like Conditional for practical reasons.

I'm not as opposed to adding these things as I originally was, but I think if we do syntax changes we should do them all in one go and make a breaking change. I'm open to proposals, but we should solicit input from other folks as well for any change like this.

**Comment by mathisonian** [comment]
I'd be in favor of adding this as 

```
~ x = 10 // [var name:"x" value:10 /]
~ y := 10  // [derived name:"x" value:`10` /]
```

to avoid clashing with the existing markdown list syntax.

**Comment by rollaball** [comment]
One way to implement this would be to add a lexer rule to generate separate `var` components for every variable in the given line.
This would mean there is no need for any change in runtime.
Would this be the right way or should this be handled in runtime separately?

**Comment by mathisonian** [comment]
That seems like the right way to me @rollaball. We would want to leave the AST/Runtime untouched if possible and just have this change impact the compiler.
