### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [idyll-lang/idyll#409]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if Idyll would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by mathisonian** [comment]
Cool, the logo that you have looks good to me! Thanks for all the hard work on KaTeX ✨

**Comment by ylemkimon** [comment]
@mathisonian Thank you ❤️
