### ISSUE TITLE
Radio component gives few React warnings

### ISSUE THREAD

**Issue by tanalan** [idyll-lang/idyll#423]
React gives a warning when the [Radio](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-components/src/radio.js) is used, as it looks like each children in the radio array needs to have a unique prop. There are also other warnings (attached picture).

<img width="634" alt="screen shot 2018-10-02 at 4 05 03 pm" src="https://user-images.githubusercontent.com/12927245/46381869-000e5e80-c65d-11e8-8c52-49128135587a.png">

**Comment by mathisonian** [comment]
fixed in #425
