### ISSUE TITLE
command line flags overriden by package.json config

### ISSUE THREAD

**Issue by tanalan** [idyll-lang/idyll#426]
**Describe the bug**
I'm having trouble getting idyll to recognize the command line flags.
For example, running `idyll --layout centered` doesn't give a centered layout; it gives the default blog layout.

This also happens in a new project I create with `idyll create`. I'm on the latest version of idyll too @3.8.3.

Upon some investigation, I noticed that on older projects, the command line flags do work. I see that in their `package.json` files, they do **not** have the `idyll` attribute, whereas the `package.json` files of my newer projects **do** have the `idyll` attribute, which has the default blog/theme/css values.

If I change the attribute to centered inside `package.json`, then it'll work as expected.
Is there something I'm missing? Perhaps I'm setting the flags incorrectly.

**To Reproduce**
1. `idyll create newProjectName`
2. `cd newProjectName`
3. `idyll --layout centered`
4. But then the layout still is the default blog layout :[

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

** Misc. **
I first noticed this when I tried adding an `authorView` flag to #410 , via `idyll --authorView true`, but then the `runtime.js` didn't seem to  recognize this flag.

**Comment by mathisonian** [comment]
Hey @tanalan,

In idyll v3 we switched away from command line flags in favor of using a config file. The `package.json` that is generated with `idyll create` has an `idyll` field, which is the canonical place to put build options now, although I'd expect CLI options to still work, I think theres some interaction where the package.json is given priority. 

For testing `authorView` I'd suggest just adding that to the `package.json` field and see if that improves the situation.

**Comment by tanalan** [comment]
Mmk, thanks, sounds good! I will do that.

(Also oops I accidentally closed the issue xD)

**Comment by mathisonian** [comment]
@manjhawar96 - this might be a good first issue to tackle on the CLI side. It seems for some reason the configuration from package.json is taking precedence over command line flags, and I think thats a bug.
