### ISSUE TITLE
Improved Documentation on Embedding Idyll in React

### ISSUE THREAD

**Issue by witang** [idyll-lang/idyll#429]
I apologize in advance if resources for this already exist and I've just overlooked them, but would it be possible to write more documentation in regards to embedding Idyll within existing React applications? From what I can see, this is the only documentation available on the subject: [https://idyll-lang.org/docs/publishing/embedding](https://idyll-lang.org/docs/publishing/embedding). 

From my own exploration, it seems that the IdyllDocument component is explicitly expecting the raw Idyll markup as a String in the "markup" prop. And while I'm able to get basic Idyll markup to render in the React app, it doesn't seem capable of handling more complex components such as if I pass an IdyllVegaLite component in the raw markup string. 

Ideally, I would love to build a React application that embeds a wide variety of Idyll documents from various users, but I'm having some difficulty purely based off of the current documentation. 

Thank you.

**Comment by mathisonian** [comment]
Thanks @witang, agree that the documentation there could use some work.

You've found most of the functionality already, but there is some additional work needed to render custom components. Here's an example using IdyllVegaLite that might help:

```
import IdyllDocument from 'idyll-document';
import * as components from 'idyll-components';
import IdyllVegalite from 'idyll-vega-lite';

const availableComponents = {
   ...components,
   IdyllVegaLite: IdyllVegaLite
}

// An example functional component
({ idyllMarkup }) => {
  return (
    <IdyllDocument
      markup={ idyllMarkup }
      components={ availableComponents }
      datasets={ {} } />;
  )
}
```

Internally it will try to match components found in the Idyll markup to anything that looks like a match in the component map provided.

**Comment by witang** [comment]
Thanks a lot @mathisonian. That definitely helps. 

So based on that example, it seems to follow that if I use my own custom React components in an Idyll document, and then embed said document in a larger React app, then those custom React components would also need to be added to the set of "availableComponents" passed to the "components" prop? 

Additionally, for the "datasets" prop, what format does that prop expect the data in? My Idyll documents currently read from basic CSV files, but I'm not sure how those would be passed to support the component once embedded in React.

**Comment by mathisonian** [comment]
Yes, thats correct. By embedding directly in React rather than using the CLI you gain some flexibility, but have to do some extra work that the CLI would usually do to get everything functional.

The datasets will need to be provided as JSON in a similar fashion, e.g. 

```
    <IdyllDocument
      markup={ idyllMarkup }
      components={ availableComponents }
      datasets={ { myDataset: [row1, row2, ..., rowN ] } } />;
```

To quickly convert basic CSV files to JSON, I'd recommend https://shancarter.github.io/mr-data-converter/

**Comment by mathisonian** [comment]
One idea that's been thrown around is having a CLI option to generate a standalone component rather than a full HTML page. I'm curious if that's something that would be useful for you.

**Comment by witang** [comment]
Great, thanks. That's extremely helpful. I really appreciate the fast response times @mathisonian.

As for your second comment, I definitely agree that having a CLI option to generate standalone components would be a welcome feature. Personally, I think being able to work with React components as opposed to passing around raw markup Strings would be cleaner in many cases.

**Comment by witang** [comment]
Sorry to bother you again @mathisonian, but as another follow-up, how do you perform advanced configurations on Idyll components being embedded in React? For example, if I want to override the default CSS styling or impose a custom HTML template, how do I pass that to the component? 

I know that if I was simply rendering a standalone Idyll page that I would be able to set all of this in the package.json, but I haven't been able to find anything on doing this with embedded Idyll (unless we're meant to configure this in the package.json of the enclosing React application)?

**Comment by mathisonian** [comment]
Thanks @witang, and no worries at all, feel free to continue asking as many questions as you like 😄 conversations like these help us figure out what's lacking in the documentation, and what type of improvements should be made in the future.

For reference here are all the available properties that can be passed in to Idyll document:

```
<IdyllDocument
    ast={ast} /* optional, if you want to pass in a precompiled abstract syntax tree instead of markup */
    components={components} /* Map of components that may be referenced in markup */
    context={context} /* Add custom context hooks (see https://idyll-lang.org/docs/advanced-configuration) for more info */
    datasets={datasets} /* Map of datasets that may be referenced in markup */
    layout={layout} /* Which layout to use? e.g. "blog", "centered" */
    markup={markup} /* String of Idyll markup. Must provide either this OR ast */
    theme={theme} /* Which theme to use? e.g. "github" */
/>
```

If you want to add CSS that overrides the styles built into the Idyll themes/layouts, you should be able to do that through standard CSS, however you're comfortable doing that on the React side (a standard stylesheet import would do).

In terms of providing a custom HTML template, I'm not sure what that would look like if you are embedding in React, given that it kind of already is rendering inside a custom template, i.e. whatever you decide to put on the page using React. I'm curious about what exactly you're trying to accomplish with this, I might be able to help point to some solutions.

**Comment by mathisonian** [comment]
Added these note to https://idyll-lang.org/docs/publishing/embedding

**Comment by witang** [comment]
That looks awesome. Thanks @mathisonian
