### ISSUE TITLE
Documentation: custom components should inherit from React.PureComponent

### ISSUE THREAD

**Issue by ChristianFrisson** [idyll-lang/idyll#440]
**Describe the bug**
The documentation should state that [custom components](https://idyll-lang.org/docs/components/custom) should inherit from `React.PureComponent` instead of `React.Component` so that rendering is updated only on properties or state changes. This speeds up compilation in watch mode.

**To Reproduce**
Steps to reproduce the behavior: create a custom component using the [documentation](https://idyll-lang.org/docs/components/custom).

**Expected behavior**
The custom component [documentation](https://idyll-lang.org/docs/components/custom) should illustrate examples of components that inherit from `React.PureComponent` instead of `React.Component`. 

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: independent
 - Browser: independent
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: indedepent
 - OS: N/A
 - Browser: independent
 - Version: N/A

**Additional context**

Article [React.PureComponent’s children](https://blog.cloudboost.io/react-purecomponents-children-979e3da15ba8) by Bobby The Doggy on Dec 18, 2017 provides details.

**Comment by mathisonian** [comment]
Closed by #441, I'll push an update to the live docs site momentarily.
