### ISSUE TITLE
Error when using idyll create and entering full path

### ISSUE THREAD

**Issue by Harmon758** [idyll-lang/idyll#446]
**Description**
An error occurs when using `idyll create` and entering the full path when prompted for the install directory:
```
C:\Users\User\Desktop\Example>idyll create

? In which directory would you like to install your post? C:\Users\User\Desktop\Example\test
? What would you like to name your post? testing

Creating a new Idyll post in C:\Users\User\Desktop\Example\test using the basic template...
√  Ensuring that the target directory is valid
√  Copying files from template directory into the target directory
√  Configuring post
-  Installing dependenciesevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\User\AppData\Roaming\npm\node_modules\idyll\node_modules\cross-spawn\lib\enoent.js:34:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Reproduction Steps**
1. Open terminal
2. Enter `idyll create`
3. Enter a full path for the install directory
4. Enter anything for the name
4. Wait and see error

**Expected Behavior**
Either an error rejecting the full path input or no error when creating the post

**Screenshots:** N/A

**Desktop:**
 - OS: Microsoft Windows 7 (64-bit) [Version 6.1.7601]
 - Browser: N/A
 - Version: 3.12.0

**Smartphone:** N/A

**Additional Context**
This occurs because `installDependencies` joins the current working directory with the input for the install directory:
https://github.com/idyll-lang/idyll/blob/697fe62e2e97b47be45dfc227d6a51329cd4a306/packages/idyll-cli/bin/cmds/create-project.js#L146

**Comment by mathisonian** [comment]
Fixed in #451
