### ISSUE TITLE
Markdown parser: Bold and paragraph markdown interaction.

### ISSUE THREAD

**Issue by rowanc1** [idyll-lang/idyll#449]
It looks like there might be a bug with the bold/paragraph interaction in the markdown implementation.

Given:
```
This is **bold text.**

Not a new paragraph.
```

There is no new paragraph after the bold text. However, not ending the paragraph with something bold gives the expected result.
```
This is **bold** text.

New paragraph!
```

Output:
![image](https://user-images.githubusercontent.com/913249/50665750-20f19300-0f6f-11e9-8e04-99cfdfa0603b.png)

Idyll version: `3.12.0`

**Comment by mathisonian** [comment]
Thanks for flagging this @rowanc1, looks like a compiler bug with how the bold parser interacts with newlines.

**Comment by mathisonian** [comment]
This was fixed in https://github.com/idyll-lang/idyll/pull/470 and will go out in the next release. Apologies for the slow fix, and thanks again for reporting @rowanc1.
