### ISSUE TITLE
Available components should reload automatically

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#46]
Right now if you create a new custom component, you have to stop and restart the server to get it to show up. Thanks @rreusser for raising this

**Comment by rreusser** [comment]
Apologies on failing to file it! The simple solution seems to be to just recompute the available components every time you need it. The more sophisticated solution might be to use [chokidar](https://github.com/paulmillr/chokidar) to specifically watch certain paths (`components/*` and `components/default_components/*` ?) and reload only when it changes.
