### ISSUE TITLE
Custom formatting for `Dynamic`

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#490]
For example, I want to display note names instead of numbers.

**Comment by mathisonian** [comment]
What would the interaction look like in this case? You would drag, for example, an A note and it becomes B, etc? 

We could introduce a custom format option that maps value onto a label. This would be pretty straightforward to implement, would it work for your use case?

**Comment by suhr** [comment]
> You would drag, for example, an A note and it becomes B, etc?

Yeah.

> We could introduce a custom format option that maps value onto a label. This would be pretty straightforward to implement, would it work for your use case?

If this option is a function, sure.

**Comment by rowanc1** [comment]
I have been working on something similar in my own project:

![hsMIXmd1Bx](https://user-images.githubusercontent.com/913249/57751696-c9dd9680-76a3-11e9-88ae-d0b122770edc.gif)

I think basically looking at the syntax similar to:
```
[Dynamic transform:`(value > 0)? value : 'free'`/]
```

**Comment by mathisonian** [comment]
@codemayank how would you feel about taking this one?

**Comment by codemayank** [comment]
> @codemayank how would you feel about taking this one?

Yes, sure I'll take this one.

**Comment by mathisonian** [comment]
This has been added (see #519) and will be available in the next release. 

See https://idyll.pub/post/dynamic-test-3f0ebd38f8d30970b1da2f89/ for example usage.

**Comment by rowanc1** [comment]
Nice. :)
