### ISSUE TITLE
Support JSX file extension

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#491]
**Describe the solution you'd like**
Given that many Idyll components use JSX syntax, it would be nice to support files named with the `.jsx` file extension in addition to the standard `.js`.

**Comment by amitbadala** [comment]
@mathisonian could you elaborate?

**Comment by mathisonian** [comment]
So some people prefer to name their components like `my-component.jsx` rather than `my-component.js` if they are using React's JSX syntax in those component files, however if you try to do this now, you'll get a "component not found error" when trying to use that `my-component.jsx` file. 

To fix, we'll have to update the component resolver to be able to handle `.jsx` files. I believe the culprit for the error comes from [this line](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-cli/src/resolvers/components.js#L99). The problem could likely be solved by checking if the import worked as expected, and trying to import the `.jsx` version if the first attempt fails (although I haven't tested this logic yet!)

**Comment by amitbadala** [comment]
@mathisonian I tried reproducing.

1. Added _my-component.jsx_ file
2. Exported as _MyComponent_
3. Accessed that particular component in Idyll project using ```[MyComponent/]```
4. Also imported my-component into another component with js extension.

Didn't receive an error. Am I doing something wrong here?

**Comment by mathisonian** [comment]
Do you possibly have a copy of the file still saved as `my-component.js`? What OS are you using?

I wouldn't expect that to work! 👻

**Comment by amitbadala** [comment]
Just to be sure I had tried it with three different component names.
OS / node = Linux / 12.1.0
