### ISSUE TITLE
Improve configuration from package.json

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#492]
Currently some of the options which are exposed via the command line are not able to be configured in `package.json`. This should be reworked so that there is parity between the two.

**Comment by amitbadala** [comment]
could you provide more details?

**Comment by mathisonian** [comment]
Sure, I think there are two things here:

1) Not all of the [options](https://idyll-lang.org/docs/configuration-and-styles) that can be set via command line flags when running `idyll` can be set in `package.json`. See https://github.com/idyll-lang/idyll/blob/master/packages/idyll-cli/src/index.js#L57-L61 where we hard code options which are read from package.json. This should be re-factored so that all options can be set either via the command line or package.json

2) Running the `idyll` command will only find and read options from `package.json` if that file is found in the exact directory where `idyll` was run. It would be better to do a lookup to see if there is a `package.json` found in the current folder _or any parent folder_. This would match node.js convention that finding package.json is done through a search of ancestor directories, and would make configuring multipage projects easier, so you could have 1 top-level config instead of a config specific to each post (/cc @colinmegill)

**Comment by amitbadala** [comment]
1. What will be the flow if the user wants to use some option from its parent package.json and few options which will be specific to that particular project?
@mathisonian

**Comment by mathisonian** [comment]
I think ideally both of those package.json would be read when idyll is invoked and the child package.json would take precedence. 

So the order of precedence would be:
- command line flags (highest priority)
- local package.json
- package.json higher in the tree

**Comment by RakeshUP** [comment]
@mathisonian, Is it good enough that we search through parent folders to find 1 package.json apart from the local package.json that contains idyll key?
Because yarn seems to search the parent directories till /Users, but npm shorts when it finds directory containing node_modules folder.

**Comment by mathisonian** [comment]
@RakeshUP yes, that should be sufficient!
