### ISSUE TITLE
Two lines separated by a commented line aren't on two separate lines in the outputted html

### ISSUE THREAD

**Issue by kmdupr33** [idyll-lang/idyll#504]
**To Reproduce**
See [this idyll editor](https://idyll-lang.org/editor/64f63c44-a6ab-4e0e-8d1b-2416959f5e3f)

**Expected behavior**
If two lines are separated by a comment, the output should still have two lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/5463526/58430220-7fcabc80-8076-11e9-9b74-6aac03808402.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version  74.0.3729.169

**Comment by mathisonian** [comment]
The compiler currently just swallows comments (see https://github.com/idyll-lang/idyll/blob/master/packages/idyll-compiler/src/lexer.js#L295-L297). It seems like in some cases it should insert a `BREAK`, a la https://github.com/idyll-lang/idyll/blob/master/packages/idyll-compiler/src/lexer.js#L331

**Comment by rollaball** [comment]
fixed in #578
