### ISSUE TITLE
Decimal values don't work for props in components

### ISSUE THREAD

**Issue by kmdupr33** [idyll-lang/idyll#506]
**To Reproduce**
The docs show that we can use numbers are prop values within `index.idyll` files. However, decimal numbers result in a lexer error. See [this editor for reproduction.](https://idyll-lang.org/editor/f544128e-f463-48de-a219-fca43797cff5)

**Expected behavior**
If non-decimal numbers work, I'd expect decimal numbers to work. (or maybe this is just a documentation issue?)

**Screenshots**
![image](https://user-images.githubusercontent.com/5463526/58431291-19946880-807b-11e9-9af8-41f3872a35f2.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 74.0.3729.169

**Comment by mathisonian** [comment]
Thanks @kmdupr33 - as a workaround `[Range min:0.01 /]` should work, but we should update the matching rule [here](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-compiler/src/lexer.js#L395-L400) to have it work without a leading zero

**Comment by kmdupr33** [comment]
Got it. I can handle that. Pr incoming.
