### ISSUE TITLE
Add reference component

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#509]
**Is your feature request related to a problem? Please describe.**
A commonly requested component is for references. These are useful for referencing specific external research in a more formal way than just linking to a URL.

**Describe the solution you'd like**
A new component that can be used inline in text for citations and produces a listing of all references at the end of the article. 

This may involve creating two different components, e.g. one for creating citations and one for the listing of references. Example API:

```
Normal text, with something I want to cite [Cite source:"..." /]. 

[References /]
```

Produces:

```
Normal text, with something I want to cite [1]. 

References
[1] - Authors, Title, Etc
```

Note, I'm not sure if it is preferable to use an external resource, e.g. a bibtex file to create a listing of all the references, or to just include them all inline, e.g. `[Cite source:"Authors, Title, Etc" /]` vs `[Cite ref:"ref-name" /]`

**Comment by amitbadala** [comment]
For this, we need to share the state between [Refernces /] and [Cite /]
Was thinking of using Context in React for the same, what do you think @mathisonian?

**Comment by mathisonian** [comment]
Where would you put the context provider in that case?

**Comment by mathisonian** [comment]
I guess you could also put everything in a `cite.js` file and export two separate components:

```
[Cite ref:"ref-name" /]

[Cite.References /]
```

**Comment by rollaball** [comment]
@mathisonian can I take on this issue?

**Comment by mathisonian** [comment]
@rollaball yes! This one will be very useful for people writing technical articles in idyll

**Comment by rollaball** [comment]
We will need to maintain the context state in the parent for this as putting them in the same file still won't make it possible for them to share their states.
Would that be the right approach?

**Comment by mathisonian** [comment]
I still think it would be easiest to keep them in the same file.

Something like:

```js

const citations = {};

class References {
   render() {
     return Object.keys(citations).map(() => {
        return ...
     })
   }
}

class Cite {
  constructor() {
     citations['new-citation'] = {...}
  }

  render() {...}
}

Cite.References = References
module.exports = Cite
```

(this code is just a sketch)

**Comment by rollaball** [comment]
So the problem here would be, as the citation is not being passed as a prop and it is also not inside the state, the references component won't rerender when a new citation is added. So the references would take empty citations array.

**Comment by mathisonian** [comment]
Ah you're right, above would just work if you assume static citations with references at the end of the article. A relatively clean fix for this might be to add a custom setter method on the citations object and force an update on any reference components after a new citation info is added. 

I'm pushing for the 1-file option to keep components as self-contained as possible, which I think makes them a bit easier to reason about. IMO adding in context for this is a lot of conceptual overhead if this is the only place we're going to use it. I'm open to hearing arguments otherwise though.

**Comment by rollaball** [comment]
Added in #575
