### ISSUE TITLE
Add new examples to the gallery. 

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#517]
**Is your feature request related to a problem? Please describe.**
I haven't looked around for examples to post on the gallery recently. We should check e.g. https://github.com/idyll-lang/idyll/network/dependents and see if there are new ones that should be added. For example I think kmdupr33 has some candidates. Should we feature https://parametric.press there? 

We might also reach out to the community in Gitter & Twitter to see if they have examples.

**Describe the solution you'd like**
Add any good recent Idyll examples to the gallery.

**Comment by mathisonian** [comment]
This one should definitely be added: https://ateliercartographie.github.io/BR163/

**Comment by mrviniciux** [comment]
@mathisonian  I can grab this one, how many examples do you suppose to add to our gallery?

**Comment by mathisonian** [comment]
That would be great, thanks @mrviniciux! 

I'm in favor of being inclusive with what we add to the gallery. I don't have a firm number, just anything that we find where its clear that someone put time and effort in and it is in a reasonably "finished" state. The [dependents](https://github.com/idyll-lang/idyll/network/dependents) network is probably still the best place to look, maybe along with mentions of the `@idyll_lang` account on twitter.

**Comment by mathisonian** [comment]
Closed by #741
