### ISSUE TITLE
Equation: couldn`t convert string

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#532]
The equation:

```idyll
[Equation]
\begin{align}
p^{n} s &= p^{n - 1} s p \\ &= p^{n - 2} s p^{-2} \\&= s p^{-n}
\end{align}
[/Equation]
```

Idyll error:

```
couldn`t convert string \begin{align}
p^{n} s &= p^{n - 1} s p \\ &= p^{n - 2} s p^{-2} \\&= s p^{-n}\end{align}
```

Idyll output: the equation is rendered as raw plaintext.

UPDATE: the issue also appears in an inline equation when it contains `&` .

**Comment by mathisonian** [comment]
Hi @suhr - what's the expected output here? When I try to compile in latex I get errors related to using align inside of an equation environment.

There is a workaround for parse issues that you can use like `[Equation latex:"...latex string..." /]`

**Comment by suhr** [comment]
> what's the expected output here?

This: http://mathb.in/34498?key=df287d1fd1609c85bfe11d39dd3fa7df1400b6a3

**Comment by suhr** [comment]
So this is actually a KaTeX issue: `aligned` works fine.
