### ISSUE TITLE
Header anchors

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#535]
Headers should have anchors and contain links to the anchors.

Also, it would be nice to be also able to specify anchor name manually.

**Comment by mathisonian** [comment]
I agree it would be nice to have these id's inferred automatically and provide an easy linking method (see e.g. how its handled in GitHub README's). 

A quick solution to give an id reference is `[h1 id:"my-title"]My Title[/h1]`.

**Comment by mathisonian** [comment]
To wrap the header elements in links automatically I think the easiest solution would be to add new custom `h[1-6]` components to the standard lib that handle this wrapping.

**Comment by suhr** [comment]
In my project, I implemented [this component](https://github.com/suhr/genkey/blob/master/components/h.tsx) component with [this css](https://github.com/suhr/genkey/blob/master/styles.css#L14).

It works fine, though I'd prefer `[H2][/H2]` instead of `[H n:2][/H]`. A some kind of markdown syntax, like the one discussed [here](https://talk.commonmark.org/t/anchors-in-markdown/247) would be even better.
