### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [idyll-lang/idyll#536]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/idyll-lang/idyll/blob/master/packages/idyll-docs/package.json#L27

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by mathisonian** [comment]
Fixed in #537, thanks for the heads up
