### ISSUE TITLE
Where are commit-message guidelines?

### ISSUE THREAD

**Issue by joshuahhh** [idyll-lang/idyll#543]
When you create a PR on Idyll, the template asks you to check that "The commit message follows our guidelines". However, the "[Contributing](https://github.com/idyll-lang/idyll/blob/master/CONTRIBUTING.md)" link (on the right) does not offer any information on these guidelines.

I think that either guidelines should be added to the Contributing page, or this checkbox should be removed.

Thanks!

**Comment by mathisonian** [comment]
Thanks for pointing that out, I've removed the checkbox from the PR template. I don't think we need to police commit logs, they are usually reasonable.
