### ISSUE TITLE
Add lerna test commands to husky pre-push 

### ISSUE THREAD

**Issue by amitbadala** [idyll-lang/idyll#545]
**Is your feature request related to a problem? Please describe.**
Sometimes after making changes, we forget to run _lerna run test_ before pushing it and see our build fail on the git, which eventually leads to wastage of time and extra commits.

**Describe the solution you'd like**
We can add _prepush_ command in husky which will run the Lerna test command every time before any push command is executed.

**Describe alternatives you've considered**
Thought of adding test command to _precommit_ but that would not make sense.

**Additional context**

**Comment by amitbadala** [comment]
@mathisonian what would you suggest?

**Comment by mathisonian** [comment]
I'm in favor of this change 👍

**Comment by amitbadala** [comment]
cool then !!
