### ISSUE TITLE
Eliminate need for project files

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll#55]
It would be nice if (like markdown), you could just open up a single file and start working. The minimal project for me looks like:

```
project-dir
├─┬ components
│ └── default_components
├── package.json
└── index.idl
```

(It's a little unhappy that `_index.html` doesn't exist, but it still seems to render.) Seems like it would maybe be nice (and not fundamentally difficult?) to eliminate the need for `components` and `package.json` so that you really could just open up a file and start, then add pieces as needed. Presumably it would just override built-in defaults with more pieces as specified. This is probably more a matter of configuration than anything else.

The benefit to me is that it's easier to start from scratch and feels more like a 'language' + 'document' when it's just a file and pulls in external resources as needed, rather than the fundamental unit being a carefully organized collection of files. (= framework?)

Especially since #50, looks like shouldn't be too bad. Thoughts/opinions?

**Comment by mathisonian** [comment]
I'm in favor of this. The work breaking apart the build process should help. 

I think the biggest change needed would be to allow for `idyll` to fallback to its own copy of default components (and `_index.html`?) if none are specified.

**Comment by rreusser** [comment]
The only weird part seems like maybe managing relative vs absolute paths in local vs default components, but I bet that can be solved.
