### ISSUE TITLE
Create presentations with idyll

### ISSUE THREAD

**Issue by amitbadala** [idyll-lang/idyll#559]
**Is your feature request related to a problem? Please describe.**
What if we could add features in such a way that users can create presentations using idyll. Presentations created using Idyll will be interactive, unlike traditional ones.

**Describe the solution you'd like**
We could use carousel property to achieve similarity to traditional presentations.

**Describe alternatives you've considered**
 

**Additional context**

**Comment by mathisonian** [comment]
Hey @amitbadala, this is something I'd like to add! I think the best way to go about it would be to make a new template for presentations. 

I actually have an Idyll based-presentation that we can deconstruct to use as a starting point. It was made for a private project so I need to spend a little time removing info first.

**Comment by amitbadala** [comment]
lmk how can I help, would love to work on this.

**Comment by mathisonian** [comment]
I've just pushed the rough presentation I had set up to https://github.com/mathisonian/idyll-slideshow-draft. 

I'd check out that repo and play around with it a bit, you'll see its very bare bones but is a good start. I think we'll want to make sure there are reasonable default styles and that things work okay on mobile
