### ISSUE TITLE
Security vulnerability in mem dependency

### ISSUE THREAD

**Issue by Harmon758** [idyll-lang/idyll#561]
The version of yargs being used has a mem dependency with a security vulnerability:
https://github.com/sindresorhus/mem/issues/14 (Fixed with https://github.com/sindresorhus/mem/commit/da4e4398cb27b602de3bd55f746efa9b4a31702b / https://github.com/sindresorhus/mem/pull/19)
https://github.com/sindresorhus/os-locale/pull/31
https://github.com/yargs/yargs/issues/1209 (Fixed with yargs>=12.0.2: https://github.com/yargs/yargs/commit/efc0970bc8f91359905882b6990ffc0786193068 / https://github.com/yargs/yargs/pull/1195)

Dependency hierarchy:
```
`-- idyll@4.5.3
  `-- yargs@8.0.1
    `-- os-locale@2.1.0
      `-- mem@1.1.0
```

https://github.com/idyll-lang/idyll/blob/43ac3aa6252a4bd43c3f26cfefd9275d1678e94f/packages/idyll-cli/package.json#L73

GitHub has recently started creating security alerts for this vulnerability:
![image](https://user-images.githubusercontent.com/9403740/61253685-6adde180-a727-11e9-8e2f-a63dbd5c62ee.png)

**Comment by mathisonian** [comment]
I haven't seen a security alert for this yet - we released a dependency update a few days ago (https://github.com/idyll-lang/idyll/pull/558) is it possible this is already fixed in the latest?

**Comment by Harmon758** [comment]
Resolved by https://github.com/idyll-lang/idyll/commit/8610555bedc07a9313b6e67a3451aa618e488e2d (#562) in idyll@4.6.0.
