### ISSUE TITLE
Scrollytelling template

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#563]
**Is your feature request related to a problem? Please describe.**
As we're adding more templates (basic post, blog, slideshow, ...) it would be nice to include one that makes it easy to get started with a "scrollytelling" project. @megan-vo's [example](https://idyll.pub/post/stack-scroll-0c3da7fb8e45f3ecb720bcf8/) would probably be a good place to start (src [here](https://github.com/megan-vo/stacked-scrolling-tutorial); it will need to be updated for idyll v4). 

**Describe the solution you'd like**
Add a new template that serves as a jumping off point for creating scroll-driven multi-section posts.

**Comment by rollaball** [comment]
@mathisonian 
Is [this](https://idyll.pub/post/test-post-a3ddd0fc526528f361ffd092/) what we are looking for here?
What should be changed here??

**Comment by mathisonian** [comment]
Yes that is looking good! 

Could you add a second scroller, so it is clear how they can be "stacked"? For the second one maybe just use a different solid back background color rather than a fixed graphic.
