### ISSUE TITLE
Sublime syntax highlighting

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#572]
There seems to be no syntax highlighting plugin for sublime text.

**Comment by RakeshUP** [comment]
@mathisonian, I have done the syntax highlighting plugin for sublime text 
Can you create a new repo in idyll-lang, to which I'll push the plugin? 
And after you review it, I will raise a release request in Sublime package control. 
Or shall I create a repo in idyll-lang?

**Comment by mathisonian** [comment]
That's great @RakeshUP! 

I made a repo for it here: https://github.com/idyll-lang/idyll-sublime-syntax-highlighter

If you push what you have to that repo now, I'll leave comments there, and you can cut the release.

**Comment by RakeshUP** [comment]
@mathisonian, The Idyll-syntax highlighter has released in Sublime Package Control Repo!
It is named Idyll-syntax. 
Can we close this issue?

cc/ @suhr
