### ISSUE TITLE
idyll-document datasets prop ineffective

### ISSUE THREAD

**Issue by declann** [idyll-lang/idyll#582]
Hi,

Excellent work on Idyll.

I am trying to integrate it in React and I'm running into an issue passing datasets in using the datasets prop. I've found no documentation on this, so I gave it a stab passing an object literal like `{ dataset: [ {d1: ...,...} ] }`

I did minimal debugging and saw that the prop is used here in a call to getData:
https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/runtime.js#L282
and in getData `arr.reduce(pluck, {})` is called, but arr in here is an empty object so this basically does nothing.

Of course, if I am using this prop incorrectly, please let me know.

Thanks,
Declan

**Comment by mathisonian** [comment]
Hey @declann,

You can pass in datasets as an object with the keys referring to the data `name` and the value being the parsed value of the dataset. For example, if I include in the markup

```
[data name:"myData" source:"data.json" /]
```

then the datasets prop will be populated as `{ myData: [{"x": 1, "y": 2}, {"x": 3, "y": 5}] }`. 

This should be better documented, I'll make an issue to update the docs and the `idyll-document` README. This API was originally designed with internal use in mind, so if there's anything you find difficult to accomplish let us know and we can figure out how to streamline.

**Comment by declann** [comment]
I have this working now, thanks for the speedy response @mathisonian !
