### ISSUE TITLE
Delete prefix to author in header component

### ISSUE THREAD

**Issue by TomBor** [idyll-lang/idyll#593]
**Is your feature request related to a problem? Please describe.**
The prefix "By:" to the author property in header component is useful when you write in english but for other language it's a problem.

**Describe the solution you'd like**
Delete the prefix or add a new property to overwrite a default prefix.

**Comment by mathisonian** [comment]
Thanks for pointing this out @TomBor. I agree this is an issue and we shouldn't assume the output is English. A similar problem will occur when multiple author names are provided (they are joined with the english word "and").

**Comment by jprask** [comment]
Hey @mathisonian, I could work on this. We could add a `bylineTemplate` prop that overrides the defaults, i.e.

```
  bylineTemplate: {
    prefix: 'Authors:',
    joint:' - '
  }
```
for `Authors: A - B - C`

A fancier approach could use a render prop, so the template would be a function that gets the authors array and outputs some jsx.

**Comment by mathisonian** [comment]
That makes sense to me @jprask! I think we'd want both a `join` option and a terminating join, e.g. in the case of `A, B, and C`. 

A function seems like maybe overkill, but we could always do a typecheck in the component to see if an object or a function is passed, and handle accordingly.
