### ISSUE TITLE
Persist variables

### ISSUE THREAD

**Issue by thSoft** [idyll-lang/idyll#596]
**Is your feature request related to a problem? Please describe.**
The value of variables reset to the default value when the page is reloaded or the browser unexpectedly crashes. When the document is a longer explorable explanation, it might be desirable that they be preserved since they are the result of the user's interaction that should not be lost.

**Describe the solution you'd like**
Introduce a property `persistent` for variable declaration:

```
[var name:'x' value:10 persistent:'local' /]
```

**Describe alternatives you've considered**
There might be two scopes of persistence: device (using LocalStorage or similar API) or user (using Firebase or similar storage service).

**Comment by mathisonian** [comment]
@thSoft there is a version of this with https://github.com/idyll-lang/idyll-plugin-url-state, though it is limited according to what can be persisted via a query string. It might be a good jumping off point to consider other back-ends, e.g. localstorage.

**Comment by thSoft** [comment]
Great, this might be a good approach, thanks!

**Comment by mathisonian** [comment]
@thSoft did you ever end up trying this out? I'd like to make a localstorage plugin at some point, wondering if you have any code you've been working with.

**Comment by thSoft** [comment]
Unfortunately currently I don’t have time to investigate this, but both approaches seem fine. Persisting data in the URL has the advantage of being easily shareable, however the data that could be persisted can be more limited.


2020. febr. 12. dátummal, 23:17 időpontban Matthew Conlen <notifications@github.com <mailto:notifications@github.com>> írta:

**Comment by mathisonian** [comment]
Closing this since it isn't a bug in idyll and can be added via a plugin. Please post if anyone ends up building this!
