### ISSUE TITLE
Header component byline not applying template (By: , and)

### ISSUE THREAD

**Issue by jprask** [idyll-lang/idyll#600]
**Describe the bug**
By line does not apply prefix, suffix & joint when authors array is provided & author has no link.

**To Reproduce**
For example, the following code

```
[Header
  title:"The article"
  subtitle:"Bottom text"
  authors:`[
    'Artie', 'Bill', 'Carl', 'Daniel'
  ]`
/]

```

will render this:

![image](https://user-images.githubusercontent.com/28638133/69830805-3c0f6600-1205-11ea-863b-56b127ebdfe0.png)

**Expected behavior**
It should join the authors with a comma, and add the word `and` before the last one like so:

![image](https://user-images.githubusercontent.com/28638133/69830862-7da01100-1205-11ea-8cc5-4b8c26c5e4ec.png)

**Additional context**
Found this working on the byline template feature, got a draft of a solution that can be discussed once #599 is merged if all of this makes sense

**Comment by mathisonian** [comment]
Hey @jprask is this still an issue? If you have a draft of something I'd be happy to review.

**Comment by jprask** [comment]
Looking into it...
