### ISSUE TITLE
Project templates include bare URL that idyll compiles to a 404 link

### ISSUE THREAD

**Issue by apellis** [idyll-lang/idyll#614]
**Describe the bug**
The four template pages

-   packages/idyll-template-projects/templates/article/index.idyll
-   packages/idyll-template-projects/templates/multipage/posts/post-1/index.idyll
-   packages/idyll-template-projects/templates/multipage/template/index.idyll
-   packages/idyll-template-projects/templates/scrollytelling/index.idyll

each contain a bare URL pointing to the idyll docs. The idyll compiler compiles these into links. But since there is a comma adjacent to the end of each link, the idyll compiler includes the comma in the linked-to URL, causing a 404 upon clicking the link.

**To Reproduce**
1. Create a new project using any of the four templates listed above
2. Build, run, and navigate to the relevant page
3. Click the link to https://idyll-lang.org/docs/
4. See 404 and note trailing comma in the browser bar

**Expected behavior**
No trailing comma, correct link to idyll docs

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Chrome
 - Version 79.0.3945.130

**Comment by mathisonian** [comment]
Fixed by #615
