### ISSUE TITLE
Minor CSS issue with fixed graphic in scroller

### ISSUE THREAD

**Issue by lcyraphael** [idyll-lang/idyll#618]
**Describe the bug**
There's some extra whitespace in the right margins in the scrollytelling template. This introduces a horizontal scroll bar across the whole page which shouldn't be there.

**To Reproduce**
1. `idyll create`
2. Pick scrollytelling
3. `idyll`

**Expected behavior**
Some overflowing margin on the right, which I think is caused by the fixed graphic in the scroller.

**Screenshots**
![image](https://user-images.githubusercontent.com/1427186/75881378-d4c20d00-5e16-11ea-8a93-c47fa37d1477.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox, Chrome, Opera 
 - Idyll v4.10.1

**Fix**
I think the below fixes it. If someone can verify it's not a breaking change, that'd be great 😄 
```
.idyll-scroll-graphic {
  overflow: hidden;
}
```

**Comment by mathisonian** [comment]
Closing as this was fixed in #619
