### ISSUE TITLE
idyll-lang.org website: early Google Analytics tag breaks entire website rendering when www.google-analytics.com fails to load

### ISSUE THREAD

**Issue by sietse** [idyll-lang/idyll#620]
This issue pertains to the idyll-lang.org website. I could not find a separate repository for that website. If this is the wrong place to report this issue, could you perhaps point me to the correct place to submit this issue? I apologize for the inconvenience.

### Steps to reproduce

1. Block the www.google-analytics.com domain. On Linux you can do this by editing /etc/hosts and adding the line `0.0.0.0 www.google-analytics.com`; also any ad-blocker worth its salt will block that domain, or let you block it manually.

2. Surf to https://idyll-lang.org

### Observed result

Browser shows a blank page, even when the page is done loading. Using the browser's View Source or Inspect Element functionality shows that the page has loaded, it just doesn't get rendered.

### Expected result

That the website displays normally, and does not break when Google Analytics is unavailable.

When either google-analytics.com or fonts.googleapis.com fails to load, for example because the user has blacklisted those domains, the web page doesn't display at all

### How to fix

Find the tag `<script async="" src="https://www.google-analytics.com/analytics.js"></script>` and move it to the very end of the `<body>` contents. That way, when it fails to load, everything before it will still get rendered normally and the user will notice nothing wrong.

**Comment by mathisonian** [comment]
Hi @sietse thanks for reporting this.

The code that adds the Google analytics to the docs site is here: https://github.com/idyll-lang/idyll/blob/master/packages/idyll-docs/components/analytics.js#L5-L9 

We should add some error handling logic to ensure that this doesn't crash the page if the server can't be reached.
