### ISSUE TITLE
Better documentation on use of HTML tags

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#621]
**Is your feature request related to a problem? Please describe.**
The docs should clearly expose how HTML tags can be used in Idyll markup, including how you can set class names and inline styles. 

For example, you could write 

```
[span className:"my-custom-text" style:`{color: 'red'}`] 
    my custom styled text
[/span]
```

**Describe the solution you'd like**
A new section in the docs, titled "using HTML tags" that includes the above info.

**Describe alternatives you've considered**
We could embed this information somewhere else, but then it is hard to find.

**Additional context**
Thanks @geoffreylitt for pointing this out.

**Comment by gerudo7** [comment]
I would be interested in working on this documentation this week. My current plan is to discuss use of css, the style section, and inline styles for `div`, `p`, and `span` as well as cover some of the simpler tags (like `[br /]` and `[i][/i]`). Something I've noticed is that certain options (mainly `background-color`) don't work with inline tags, but do work if defined in a class - is this something I should document, or is it a bug?

**Comment by mathisonian** [comment]
Hey @gerudo7! 

That sounds good. Things with dashes like `background-color` get set via a camel case version of the name, so you can write 

``[div style:`{backgroundColor: 'blue' }` /]``

**Comment by gerudo7** [comment]
Ah, that makes sense, thank you!
