### ISSUE TITLE
Improve documentation for getting started with multipage template

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#632]
**Is your feature request related to a problem? Please describe.**
Currently the multipage template isn't the most user friendly; users have to read the local README file that gets generated in order to figure out how to do things like create new posts. There is no high-level guide that shows you how to get started quickly as was pointed. out in https://gitter.im/idyll-lang/Lobby?at=5ea21041568e5258e47dc274. 

**Describe the solution you'd like**
The documentation should be improved with a "quick start" section in the README and online.

**Comment by gerudo7** [comment]
I am planning to work on this documentation this week.

**Comment by mathisonian** [comment]
Thanks @gerudo7! That would be greatly appreciated - feel free to post here if you run into any issues or have questions.

**Comment by gerudo7** [comment]
Where is the best place for the online entry? Of the existing categories in the online documentation, it seems to fit best in "Overview", but I'm not sure if it's too specific to fall there.

**Comment by mathisonian** [comment]
Maybe the best place to add it would be a new subsection under the Overview, something like "Multipage template" or "Using Idyll for blogging"

<img width="175" alt="Screen Shot 2020-06-22 at 9 29 28 AM" src="https://user-images.githubusercontent.com/1074773/85311840-e0d7e600-b46a-11ea-9236-5f25f43d5f20.png">
