### ISSUE TITLE
What's the opposite of progressive enhancement?

### ISSUE THREAD

**Issue by jromero2k** [idyll-lang/idyll#660]
**Describe the bug**

Even after enabling JS, unless the GitHub button, all images, and all fonts are loaded, the website shows a blank page ("uncaught error on promise" or something like it). If there's any network failure, the same.

**To Reproduce**
1. Disable JavaScript or image/font loading
2. See a totally blank page, no indication whatsoever of what requirement was missing

**Expected behavior**
Either a message advising to activate JS, or the webpage showing full but missing some hero image or fancy font / icon, or better, the webpage rendering even if JS is disabled

**Screenshots**
Just imagine a big rectangle full of white.. that's it

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Check https://duckduckgo.com/?q=progressive+enhancement

**Comment by mathisonian** [comment]
Related to https://github.com/idyll-lang/idyll/issues/620. We're deploying a new version of the docs soon which may fix this, but I'll leave it open until that's confirmed.

**Comment by mathisonian** [comment]
This is fixed in the latest
