### ISSUE TITLE
Errors on /editor page after docs upgrade

### ISSUE THREAD

**Issue by craigdrayton** [idyll-lang/idyll#661]
https://idyll-lang.org/editor

**Comment by mathisonian** [comment]
Thanks for flagging this @craigdrayton. We're in the process of migrating the site and are hitting a few growing pains with it. Will get this fixed ASAP

**Comment by mathisonian** [comment]
The 500 error is fixed, but I've had to disable the _save_ functionality for the moment. Renaming the issue to cover a slightly broader topic.
