### ISSUE TITLE
Installation error:  Unexpected end of JSON input while parsing near '...","react-syntax-highl'

### ISSUE THREAD

**Issue by kartikpaliwal** [idyll-lang/idyll#669]
Facing this error while instaling it via npm.
I tried clearning cache too, and reinstalling npm too.

Full Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'idyll' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session 4d03704f2e1f9b60
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/idyll 17ms (from cache)
8 silly pacote tag manifest for idyll@latest fetched in 31ms
9 timing stage:loadCurrentTree Completed in 50ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule idyll@4.12.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/browserify-incremental 58ms (from cache)
18 silly pacote range manifest for browserify-incremental@^3.1.1 fetched in 60ms
19 silly resolveWithNewModule browserify-incremental@3.1.1 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/bs-pretty-message 2ms (from cache)
21 silly pacote range manifest for bs-pretty-message@^1.0.8 fetched in 3ms
22 silly resolveWithNewModule bs-pretty-message@1.0.8 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/babelify 469ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/chalk 399ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/babel-preset-react 474ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/brfs 467ms (from cache)
27 silly pacote range manifest for babelify@^7.3.0 fetched in 476ms
28 silly resolveWithNewModule babelify@7.3.0 checking installable status
29 silly pacote range manifest for chalk@^2.4.1 fetched in 405ms
30 silly resolveWithNewModule chalk@2.4.2 checking installable status
31 silly pacote range manifest for babel-preset-react@^6.22.0 fetched in 480ms
32 silly resolveWithNewModule babel-preset-react@6.24.1 checking installable status
33 silly pacote range manifest for brfs@^1.4.3 fetched in 475ms
34 silly resolveWithNewModule brfs@1.6.1 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/babel-register 482ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/babel-preset-stage-2 484ms (from cache)
37 silly pacote range manifest for babel-register@^6.24.1 fetched in 494ms
38 silly resolveWithNewModule babel-register@6.26.0 checking installable status
39 silly pacote range manifest for babel-preset-stage-2@^6.24.1 fetched in 499ms
40 silly resolveWithNewModule babel-preset-stage-2@6.24.1 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/babel-preset-env 506ms (from cache)
42 http fetch GET 200 https://registry.npmjs.org/dev-null 11ms (from cache)
43 silly pacote range manifest for babel-preset-env@^1.6.0 fetched in 512ms
44 silly resolveWithNewModule babel-preset-env@1.7.0 checking installable status
45 silly pacote range manifest for dev-null@^0.1.1 fetched in 17ms
46 silly resolveWithNewModule dev-null@0.1.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/bluebird 510ms (from cache)
48 silly pacote range manifest for bluebird@^3.5.0 fetched in 517ms
49 silly resolveWithNewModule bluebird@3.7.2 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/idyll-ast 12ms (from cache)
51 http fetch GET 200 https://registry.npmjs.org/idyll-compiler 3ms (from cache)
52 silly pacote range manifest for idyll-compiler@^4.0.13 fetched in 5ms
53 silly resolveWithNewModule idyll-compiler@4.0.13 checking installable status
54 http fetch GET 304 https://registry.npmjs.org/browser-sync 523ms (from cache)
55 silly pacote range manifest for browser-sync@^2.18.8 fetched in 530ms
56 silly resolveWithNewModule browser-sync@2.26.12 checking installable status
57 http fetch GET 200 https://registry.npmjs.org/idyll-components 10ms (from cache)
58 silly fetchPackageMetaData error for idyll-components@^3.12.2 Unexpected end of JSON input while parsing near '...","react-syntax-highl'
59 http fetch GET 304 https://registry.npmjs.org/browserify 536ms (from cache)
60 http fetch GET 200 https://registry.npmjs.org/idyll-layouts 11ms (from cache)
61 silly pacote range manifest for browserify@^16.5.0 fetched in 546ms
62 silly resolveWithNewModule browserify@16.5.2 checking installable status
63 silly pacote range manifest for idyll-layouts@^3.0.6 fetched in 14ms
64 silly resolveWithNewModule idyll-layouts@3.0.6 checking installable status
65 http fetch GET 200 https://registry.npmjs.org/idyll-document 21ms (from cache)
66 http fetch GET 200 https://registry.npmjs.org/idyll-template-projects 6ms (from cache)
67 silly pacote range manifest for idyll-template-projects@^2.2.3 fetched in 9ms
68 silly resolveWithNewModule idyll-template-projects@2.2.3 checking installable status
69 http fetch GET 200 https://registry.npmjs.org/idyll-themes 9ms (from cache)
70 silly pacote range manifest for idyll-themes@^3.0.4 fetched in 24ms
71 silly resolveWithNewModule idyll-themes@3.0.4 checking installable status
72 silly pacote range manifest for idyll-ast@^2.0.9 fetched in 70ms
73 silly resolveWithNewModule idyll-ast@2.0.9 checking installable status
74 silly pacote range manifest for idyll-document@^3.2.2 fetched in 55ms
75 silly resolveWithNewModule idyll-document@3.2.2 checking installable status
76 http fetch GET 304 https://registry.npmjs.org/change-case 130ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/cross-spawn 128ms (from cache)
78 silly pacote range manifest for change-case@^3.0.1 fetched in 134ms
79 silly resolveWithNewModule change-case@3.1.0 checking installable status
80 silly pacote range manifest for cross-spawn@^6.0.5 fetched in 132ms
81 silly resolveWithNewModule cross-spawn@6.0.5 checking installable status
82 http fetch GET 304 https://registry.npmjs.org/debug 133ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/html-tags 103ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/fs-extra 117ms (from cache)
85 silly pacote range manifest for debug@^3.1.0 fetched in 143ms
86 silly resolveWithNewModule debug@3.2.6 checking installable status
87 silly pacote range manifest for html-tags@^1.1.1 fetched in 114ms
88 silly resolveWithNewModule html-tags@1.2.0 checking installable status
89 silly pacote range manifest for fs-extra@^5.0.0 fetched in 127ms
90 silly resolveWithNewModule fs-extra@5.0.0 checking installable status
91 http fetch GET 304 https://registry.npmjs.org/csv-parse 148ms (from cache)
92 silly pacote range manifest for csv-parse@^4.8.2 fetched in 154ms
93 silly resolveWithNewModule csv-parse@4.12.0 checking installable status
94 http fetch GET 304 https://registry.npmjs.org/inquirer 102ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/insert-css 89ms (from cache)
96 silly pacote range manifest for inquirer@^5.2.0 fetched in 109ms
97 silly resolveWithNewModule inquirer@5.2.0 checking installable status
98 silly pacote range manifest for insert-css@^2.0.0 fetched in 93ms
99 silly resolveWithNewModule insert-css@2.0.0 checking installable status
100 http fetch GET 200 https://registry.npmjs.org/resolve 5ms (from cache)
101 silly pacote range manifest for resolve@^1.3.3 fetched in 7ms
102 silly resolveWithNewModule resolve@1.17.0 checking installable status
103 http fetch GET 304 https://registry.npmjs.org/mkdirp 97ms (from cache)
104 silly pacote range manifest for mkdirp@^0.5.1 fetched in 100ms
105 silly resolveWithNewModule mkdirp@0.5.5 checking installable status
106 http fetch GET 304 https://registry.npmjs.org/mustache 149ms (from cache)
107 http fetch GET 304 https://registry.npmjs.org/recursive-readdir 117ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/ora 133ms (from cache)
109 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 117ms (from cache)
110 silly pacote range manifest for mustache@^2.3.0 fetched in 154ms
111 silly resolveWithNewModule mustache@2.3.2 checking installable status
112 silly pacote range manifest for recursive-readdir@^2.2.2 fetched in 125ms
113 silly resolveWithNewModule recursive-readdir@2.2.2 checking installable status
114 silly pacote range manifest for ora@^2.1.0 fetched in 144ms
115 silly resolveWithNewModule ora@2.1.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/request 141ms (from cache)
117 silly pacote range manifest for request@^2.87.0 fetched in 145ms
118 warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
119 silly resolveWithNewModule request@2.88.2 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/react 174ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/react-dom 166ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/request-promise-native 121ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/slash 114ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/svg-tags 110ms (from cache)
125 silly pacote range manifest for regenerator-runtime@^0.13.5 fetched in 176ms
126 silly resolveWithNewModule regenerator-runtime@0.13.7 checking installable status
127 silly pacote range manifest for slash@^1.0.0 fetched in 122ms
128 silly resolveWithNewModule slash@1.0.0 checking installable status
129 silly pacote range manifest for react@^16.0.0 fetched in 194ms
130 silly resolveWithNewModule react@16.13.1 checking installable status
131 silly pacote range manifest for react-dom@^16.0.0 fetched in 182ms
132 silly resolveWithNewModule react-dom@16.13.1 checking installable status
133 silly pacote range manifest for svg-tags@^1.0.0 fetched in 126ms
134 silly resolveWithNewModule svg-tags@1.0.0 checking installable status
135 silly pacote range manifest for request-promise-native@^1.0.5 fetched in 144ms
136 warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
137 silly resolveWithNewModule request-promise-native@1.0.9 checking installable status
138 http fetch GET 304 https://registry.npmjs.org/url-join 120ms (from cache)
139 http fetch GET 304 https://registry.npmjs.org/update-notifier 128ms (from cache)
140 silly pacote range manifest for url-join@^4.0.0 fetched in 123ms
141 silly resolveWithNewModule url-join@4.0.1 checking installable status
142 silly pacote range manifest for update-notifier@^2.5.0 fetched in 130ms
143 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
144 http fetch GET 304 https://registry.npmjs.org/terser 134ms (from cache)
145 silly pacote range manifest for terser@^4.3.4 fetched in 138ms
146 silly resolveWithNewModule terser@4.8.0 checking installable status
147 http fetch GET 304 https://registry.npmjs.org/yargs 105ms (from cache)
148 silly pacote range manifest for yargs@^13.3.0 fetched in 112ms
149 silly resolveWithNewModule yargs@13.3.2 checking installable status
150 timing stage:rollbackFailedOptional Completed in 0ms
151 timing stage:runTopLevelLifecycles Completed in 975ms
152 silly saveTree kartik
152 silly saveTree `-- idyll@4.12.1
152 silly saveTree   +-- babel-preset-env@1.7.0
152 silly saveTree   +-- babel-preset-react@6.24.1
152 silly saveTree   +-- babel-preset-stage-2@6.24.1
152 silly saveTree   +-- babel-register@6.26.0
152 silly saveTree   | `-- mkdirp@0.5.5
152 silly saveTree   +-- babelify@7.3.0
152 silly saveTree   +-- bluebird@3.7.2
152 silly saveTree   +-- brfs@1.6.1
152 silly saveTree   | `-- resolve@1.17.0
152 silly saveTree   +-- browser-sync@2.26.12
152 silly saveTree   +-- browserify-incremental@3.1.1
152 silly saveTree   +-- browserify@16.5.2
152 silly saveTree   +-- bs-pretty-message@1.0.8
152 silly saveTree   +-- chalk@2.4.2
152 silly saveTree   +-- change-case@3.1.0
152 silly saveTree   +-- cross-spawn@6.0.5
152 silly saveTree   +-- csv-parse@4.12.0
152 silly saveTree   +-- debug@3.2.6
152 silly saveTree   +-- dev-null@0.1.1
152 silly saveTree   +-- fs-extra@5.0.0
152 silly saveTree   +-- html-tags@1.2.0
152 silly saveTree   +-- idyll-ast@2.0.9
152 silly saveTree   +-- idyll-compiler@4.0.13
152 silly saveTree   +-- idyll-document@3.2.2
152 silly saveTree   | +-- idyll-layouts@3.0.6
152 silly saveTree   | `-- idyll-themes@3.0.4
152 silly saveTree   +-- idyll-layouts@3.0.6
152 silly saveTree   +-- idyll-template-projects@2.2.3
152 silly saveTree   +-- idyll-themes@3.0.4
152 silly saveTree   +-- inquirer@5.2.0
152 silly saveTree   +-- insert-css@2.0.0
152 silly saveTree   +-- mkdirp@0.5.5
152 silly saveTree   +-- mustache@2.3.2
152 silly saveTree   +-- ora@2.1.0
152 silly saveTree   +-- react-dom@16.13.1
152 silly saveTree   +-- react@16.13.1
152 silly saveTree   +-- recursive-readdir@2.2.2
152 silly saveTree   +-- regenerator-runtime@0.13.7
152 silly saveTree   +-- request-promise-native@1.0.9
152 silly saveTree   +-- request@2.88.2
152 silly saveTree   +-- resolve@1.17.0
152 silly saveTree   +-- slash@1.0.0
152 silly saveTree   +-- svg-tags@1.0.0
152 silly saveTree   +-- terser@4.8.0
152 silly saveTree   +-- update-notifier@2.5.0
152 silly saveTree   +-- url-join@4.0.1
152 silly saveTree   `-- yargs@13.3.2
153 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...","react-syntax-highl'
153 verbose stack     at JSON.parse (<anonymous>)
153 verbose stack     at parseJson (/usr/lib/nodejs/json-parse-better-errors/index.js:7:17)
153 verbose stack     at consumeBody.call.then.buffer (/usr/share/npm/node_modules/node-fetch-npm/src/body.js:96:50)
153 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
154 verbose cwd /home/kartik
155 verbose Linux 5.4.0-40-generic
156 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "idyll"
157 verbose node v10.19.0
158 verbose npm  v6.14.4
159 error Unexpected end of JSON input while parsing near '...","react-syntax-highl'
160 verbose exit [ 1, true ]

**Comment by mathisonian** [comment]
Hi @kartikpaliwal, can you please share your node.js version and OS?

**Comment by mathisonian** [comment]
I believe the issue is from using node v10. Using 12+ should fix the error
