### ISSUE TITLE
Render to static content

### ISSUE THREAD

**Issue by rreusser** [idyll-lang/idyll#67]
#14 covers making render-to-static *complete*, but I think we now need to back up and take a look at making it work at all. Currently the rendered output is mostly just a bare script tag. For load speed and SEO (does google run scripts now? Is that still a thing?) and just because it's a really nice feature that should hopefully be very easy, it seems like it would be nice to actually render to string.

Currently, the `require('__IDYLL_DATA__')` strategy makes it rather difficult to fake it within the main idyll process. Are those necessary or can we simply make those *inputs* to the functions that need them rather than requires?

**Comment by bclinkinbeard** [comment]
You're referring to "server side" rendering as part of the build process, right? Not sure I follow the part about the `require('__IDYLL_DATA__')` stuff but I'd love to get rid of them if possible.

**Comment by rreusser** [comment]
See: https://github.com/idyll-lang/idyll/pull/68

Yeah. Though "server side" seems like a weird term to me since I use it all the time but never on a server. I just think of it as build-time static rendering. The hierarchy that cause the problem is:

- Client bundle
  - requires `InteractiveDocument`
    - requires `__IDYLL_CONTENT__`

A reorganization that allows use of `InteractiveDocument` within idyll itself is to move the AST outside of InteractiveDocument:

- `bin/idyll`
  - computes the AST
  - pass AST to `InteractiveDocument` and then renderToStatic

Just an experiment. Unfortunately I don't see how to handle the custom components since those are obviously all jsx. 😞

**Comment by bclinkinbeard** [comment]
Oh interesting. #68 seems like the right direction, couldn't everything be passed into `InteractiveDocument`?

> I don't see how to handle the custom components since those are obviously all jsx

The pre-built versions aren't. :) Plus, doesn't `renderToStatic` support JSX?

**Comment by rreusser** [comment]
Yup! I think the right answer is indeed to pass *everything*. In fact you could then almost move `InteractiveDocument` to its own repository with… no dependencies besides maybe react?
