### ISSUE TITLE
npm install error, EINVALIDTAG

### ISSUE THREAD

**Issue by aidyp** [idyll-lang/idyll#693]
Hi,

I'm a bit new to react so i'm not 100% sure what the problem is.

When I run `npm install -g idyll` I get,
```
pm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

I have `npm version=7.5.2` and `node version=15.7.0`

Any hints on where my problem might be?

**Comment by aidyp** [comment]
Nevermind -- it was a bug on my end!

**Comment by mathisonian** [comment]
Hey @aidyp - would you mind sharing what you did to fix this? I know of at least one other report of a similar error using one node version `15`

**Comment by aidyp** [comment]
Hi, sorry for the late reply.

I didn't manage to fix it directly, but I re-installed node & npm and then got the same issue as #679 

But I'm not familiar enough with npm/node to crack that yet.
