### ISSUE TITLE
Expand test suite

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#71]
It's about time that we added a much more expansive test suite, given all the different ways in which Idyll may be used, and all the different options available. I think the first step for this is just to figure out what the structure looks like for having multiple projects in the tests folder (I believe @bclinkinbeard set this up so it should be fairly straightforward), then start testing different situations. 

Specifically, one thing I think we really need are different tests for when Idyll is included in the local node_modules, vs when it is used from the command line vs when it is used programatically. 

- `idyll`
  - [ ] command line options work
     - [ ] themes
     - [ ] component paths
     - [ ] minification and SSR
     - [ ] accepts strings or filepaths
     - [ ] watch mode
  - [ ] components
     - [ ] it finds custom components
     - [ ] it finds default components
     - [ ] it works with components from npm
     - [ ] it works with dot notation
  - [ ] server side rendering
     - [ ] variables render correctly
     - [ ] datasets render correctly
     - [ ] derived variables render correctly
- `idyll-components`
   - [ ] all components mount properly
   - [ ] all components mount properly outside of the browser (SSR)
   - [ ] what component specific tests??
- `idyll-document` - 
   - [ ] expressions work on initial mount and after updates
       - [ ] objects
       - [ ] strings 
       - [ ] variables
       - [ ] derived
       - [ ] datasets
   - [ ] basic AST renders properly
   - [ ] variable updating works
- `compiler` - tests are already pretty good there

**Comment by mathisonian** [comment]
Things to cover

- `idyll`
  - [ ] command line options work
     - [ ] themes
     - [ ] component paths
     - [ ] minification and SSR
     - [ ] accepts strings or filepaths
     - [ ] watch mode
  - [ ] components
     - [ ] it finds custom components
     - [ ] it finds default components
     - [ ] it works with components from npm
     - [ ] it works with dot notation
  - [ ] server side rendering
     - [ ] variables render correctly
     - [ ] datasets render correctly
     - [ ] derived variables render correctly
- `idyll-components`
   - [ ] all components mount properly
   - [ ] all components mount properly outside of the browser (SSR?)
   - [ ] what component specific tests??
- `idyll-document` - 
   - [ ] expressions work on initial mount and after updates
       - [ ] objects
       - [ ] strings 
       - [ ] variables
       - [ ] derived
       - [ ] datasets
   - [ ] variable updating works
- `compiler` - tests are already pretty good there

**Comment by mathisonian** [comment]
@bclinkinbeard feel free to comment with other points to hit and I can update the above comment as a master list

**Comment by bclinkinbeard** [comment]
I'll take a closer look tomorrow but this looks great based on a quick skim.
