### ISSUE TITLE
Update react-table dependency in idyll-components to latest

### ISSUE THREAD

**Issue by megan-vo** [idyll-lang/idyll#739]
The Table component in the ```idyll-components``` package is using react-table v6.11, which will no longer have long term support.

We could update react-table to the latest version as well as the Table component to implement the latest API, since it introduces breaking changes.

**Comment by mrviniciux** [comment]
I grab this @mathisonian gonna make a feasibility check first.

**Comment by mathisonian** [comment]
@mrviniciux we just got #740 merged from @megan-vo, so this can be closed now. Now we'll want to upgrade to the latest React across the project so I'll make an issue for that
