### ISSUE TITLE
Incorrect link to editor in getting started docs

### ISSUE THREAD

**Issue by OmarShehata** [idyll-lang/idyll#745]
In this page:

https://idyll-lang.org/docs/getting-started

The "online editor" link goes to: https://idyll-lang.github.io/editor, which redirects back to: https://idyll-lang.org/docs. 

I believe the correct link should be: https://idyll-lang.org/editor

**Comment by mathisonian** [comment]
Thanks for flagging this @OmarShehata. A fix is incoming via #746
