### ISSUE TITLE
Docs website error with JS enabled

### ISSUE THREAD

**Issue by FrancoRivera** [idyll-lang/idyll#756]
**Describe the bug**
When accessing https://idyll-lang.org/docs with JS enabled, the following message appears:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
---
In console:
```
Error: Cannot find module './src/container.js'
    NextJS 13
main-05ba1f4e888f481cf87c.js:1:15180
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

No issues when disabling JS

**To Reproduce**
1. Enable JS
2. Go to https://idyll-lang.org/docs
3. Message appears

**Expected behavior**
Docs should be rendered 

**Desktop:**
 - OS: MacOS Big Sur
 - Browser: Chrome (96), Firefox(94)

**Comment by vilim** [comment]
I experienced the same

**Comment by mathisonian** [comment]
I just pushed a patch in #757, docs should be back working now. Sorry for the inconvenience and thanks for reporting the issue!
