### ISSUE TITLE
Dynamic and Interactive Websites, Documents, Spreadsheets, Page Layouts and Presentations with changing and streaming data

### ISSUE THREAD

**Issue by sirinath** [idyll-lang/idyll#86]
Can we have ability to have spreadsheet (E.g. Google docs) and dynamic presentation like functionality (E.g. https://plot.ly/powerpoint-online/, http://formidable.com/open-source/spectacle/)

Also might be interested ing checking out:

 - https://github.com/stencila/stencila
 - http://orgmode.org/
 - https://en.wikipedia.org/wiki/Computable_Document_Format
 - http://escher-jl.org/
 - https://juliaplots.github.io/
 - https://www.scribus.net/
 - https://www.lyx.org/

**Comment by mathisonian** [comment]
Spreadsheet-like functionality can be achieved by using `derived` variables. A derived variable in Idyll is equivalent to a spreadsheet formula, in that you tell it how it should behave based on other values. For example:

```
[var name:"m" value:0 /]
[var name:"x" value:3 /]
[var name:"b" value:5 /]

[derived name:"y" value:`m * x +b` ]
```
to create a linear equation. We aren't interested in re-creating excel or google sheets or anything like that here. 

Dynamic presentation functionality seems like a separate issue... but the idea of having a `presentation` layout is interesting.

**Comment by sirinath** [comment]
Can we have a column, row, worksheet component which you can add data and chart. Which is rendered like this: https://plot.ly/create/ but can be fully entered like in OrgMode or Stencila.

**Comment by bclinkinbeard** [comment]
You can build a component that does whatever you want. 😀
