### ISSUE TITLE
Dashboards creating

### ISSUE THREAD

**Issue by sirinath** [idyll-lang/idyll#87]
Can we have the ability to create dashboards.

**Comment by mathisonian** [comment]
This is really outside the scope of Idyll. There are libraries specifically meant for creating dashboards, while Idyll is meant for writing and telling stories about data.

**Comment by sirinath** [comment]
You will need some what to organise the different components of the story. Some charts and text may also be context dependent.  The dashboard is all about organising the visualisation, data and story.

**Comment by mathisonian** [comment]
You could definitely create a dashboard using Idyll and custom data sources, you could probably get a long way with using flexbox for the layout, but that is something that IMO would really be different for each person's use case, and could probably be more easily be achieved with other tools. 

Is there a specific feature lacking that would help towards this goal?
